# Default values for magic-mirror.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: bastilimbach/docker-magicmirror
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# set a custom config
config:
  persistentVolumeClaim: ""
  # Address to listen on, can be:
  #   - "localhost", "127.0.0.1", "::1" to listen on loopback interface
  #   - another specific IPv4/6 to listen on a specific interface
  #   - "0.0.0.0", "::" to listen on any interface
  #   Default, when address config is left out or empty, is "localhost"
  address: "0.0.0.0"
  port: 8080
  # IP Whitelist
  #   Set [] to allow all IP addresses
  #   or add a specific IPv4 of 192.168.1.5:
  #   ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
  #   or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format:
  #   ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],
  ipWhitelist: []
  # - "127.0.0.1"
  # - "::ffff:127.0.0.1"
  # - "::1"
  # - "192.168.1.0/24"
  # - "10.0.0.0/8"

  # The language of the interface. (Note: Not all elements will be localized.)
  #   Possible values are en, nl, ru, fr, etc.
  #   default value is en.
  language: en

  # This allows to scale the mirror contents with a given zoom factor.
  zoom: 1.0

  #The form of time notation that will be used.
  # Possible values are 12 or 24.
  timeFormat: 24

  units: "metric"
  #  local for armv6l processors, default
  #  starts serveronly and then starts chrome browser
  #  false, default for all  NON-armv6l devices
  #  true, force serveronly mode, because you want to.. no UI on this device
  serverOnly: true

  # define module configurations
  modules:
  - module: alert
  - module: updatenotification
    position: top_bar
  - module: clock
    position: top_left
  - module: calendar
    header: US Holidays
    position: top_right
    config:
      calendars:
      - symbol: calendar-check
        url: "webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics"
  - module: compliments
    position: lower_third
  - module: currentweather
    postion: top_right
    config:
      location: New York
      locationId: 5128581
      appid: "YOUR_OPENWEATHER_API_KEY"
  - module: weatherforcast
    postion: top_right
    header: Weather Forcast
    config:
      location: New York
      locationId: 5128581
      appid: "YOUR_OPENWEATHER_API_KEY"
  - module: newsfeed
    position: bottom_bar
    config:
      feeds:
      - title: New York Times
        url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
      showSourceTitle: true
      showPublishDate: true
      broadcastNewsFeeds: true
      broadcastNewsUpdates: true

persistence:
  modules:
    enabled: false
    # claimName: magic-mirror-modules
  css:
    enabled: false
    # claimName: magic-mirror-modules

# synchronize the time of the host with the docker container.
localtime: true

# Probes configuration
probes:
  # probes.liveness -- Configure the healthcheck for the ingress controller
  liveness:
    enabled: false
    initialDelaySeconds: 60
    failureThreshold: 10
    timeoutSeconds: 5
  readiness:
    enabled: false
    initialDelaySeconds: 60
    failureThreshold: 3
    timeoutSeconds: 5



serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  # loadBalancerIP: "192.168.1.211"

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
