apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: plexbeat
  namespace: monitoring
spec:
  type: filebeat
  version: 7.13.2
  elasticsearchRef:
    name: elasticsearch
  kibanaRef:
    name: kibana
  config:
    filebeat:
      autodiscover:
        providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints:
            enabled: false
          templates:
          - condition.contains:
              kubernetes.pod.name: plex
            config:
            - type: filestream
              paths:
              - "/hostfs/home/stephen/data/plex/config/Library/Application Support/Plex Media Server/Logs/Plex Media*.log"
              - "/hostfs/home/stephen/data/plex/config/Library/Application Support/Plex Media Server/Logs/Plex Crash Uploader*.log"
              - "/hostfs/home/stephen/data/plex/config/Library/Application Support/Plex Media Server/Logs/Plex DLNA*.log"
              - "/hostfs/home/stephen/data/plex/config/Library/Application Support/Plex Media Server/Logs/Plex Tuner Service*.log"
              fields:
                event.dataset: "plex.server"
              ignore_inactive: since_last_start
            - type: filestream
              paths:
              - "/hostfs/home/stephen/data/plex/config/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/*.log"
              fields:
                event.dataset: "plex.plugins"
              ignore_inactive: since_last_start            
            - type: filestream
              paths:
              - "/hostfs/home/stephen/data/plex/config/Library/Application Support/Plex Media Server/Logs/Plex Transcoder Statistics.log"
              - "/hostfs/home/stephen/data/plex/config/Library/Application Support/Plex Media Server/Logs/Plex Transcoder Statistics.*.log"
              fields:
                event.dataset: "plex.transcoder"
              fields_under_root: true
              parsers:
              - multiline:
                  type: pattern
                  pattern: '^<SessionReport>'
                  negate: true
                  match: after
                  flush_pattern: '</SessionReport>$'
              processors:
              - decode_xml:
                  field: message
                  target_field: plex
                  to_lower: false
              ignore_inactive: since_last_start
                  
    processors:
    - add_host_metadata: {}
    - add_kubernetes_metadata:
        host: ${NODE_NAME}
        matchers:
          - logs_path:
              logs_path: "/hostfs/home/stephen/data/plex/config/Library/Application Support/Plex Media Server/Logs/"
  daemonSet:
    podTemplate:
      spec:
        serviceAccountname: plexbeat
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: false # Allows to provide richer host metadata
        containers:
        - name: filebeat
          securityContext:
            runAsUser: 0
            # If using Red Hat OpenShift uncomment this:
            #privileged: true
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
            limits:
              memory: 200Mi
              cpu: 100m
          volumeMounts:
          - name: hostfs
            mountPath: /hostfs
            readOnly: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
        volumes:
        - name: hostfs
          hostPath:
            path: /

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: plexbeat
  namespace: monitoring
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  - nodes
  verbs:
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: plexbeat
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: plexbeat
  namespace: monitoring
subjects:
- kind: ServiceAccount
  name: plexbeat
  namespace: default
roleRef:
  kind: ClusterRole
  name: plexbeat
  apiGroup: rbac.authorization.k8s.io



