apiVersion: v1
kind: Service
metadata:
  name: sonarr-lb
  namespace: plex
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8989
  selector:
    app: sonarr
    release: sonarr
  type: LoadBalancer
  loadBalancerIP: 192.168.1.202
