# HELM REPO: helm repo add utkuozdemir https://utkuozdemir.org/helm-charts
# CHART utkuozdemir/transmission-openvpn
# Optimized for airvpn.

replicaCount: 1

image:
  repository: haugene/transmission-openvpn
  tag: dev
  pullPolicy: IfNotPresent

dnsPolicy: "None"

dnsConfig:
  nameservers:
    - 8.8.8.8
    - 8.8.4.4

env:
  - name: OPENVPN_PROVIDER
    value: "PIA"
  - name: OPENVPN_USERNAME
    value: "p8582314"
  - name: OPENVPN_PASSWORD
    value: "EP7dpgVmtV"
  - name: OPENVPN_CONFIG
    value: "ca_ontario"
  - name: OPENVPN_OPTS
    value: "--inactive 3600 --ping 10 --ping-exit 60 --dhcp-option DNS 8.8.8.8"
#  - name: OVERRIDE_DNS_1
#    value: 8.8.8.8
#  - name: OVERRIDE_DNS_1
#    value: 8.8.4.4
  - name: LOCAL_NETWORK
    value: "192.168.1.0/24,10.1.99.1/24"
#  - name: TRANSMISSION_PEER_PORT
#    value: "51324"
  - name: TRANSMISSION_DOWNLOAD_DIR
    value: "/downloads/transmission"
  - name: TRANSMISSION_INCOMPLETE_DIR
    value: "/downloads/transmission/incomplete"
  - name: TRANSMISSION_DOWNLOAD_QUEUE_SIZE
    value: "200"
  - name: TRANSMISSION_RATIO_LIMIT
    value: "1"
  - name: TRANSMISSION_RATIO_LIMIT_ENABLED
    value: "true"
  - name: TRANSMISSION_PEER_LIMIT_PER_TORRENT
    value: "200"
  - name: TRANSMISSION_PEER_LIMIT_GLOBAL
    value: "2000"
  - name: TRANSMISSION_CACHE_SIZE_MB
    value: "16"
  - name: LOG_TO_STDOUT
    value: "true"
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"
  - name: TRANSMISSION_WEB_UI
    value: "transmission-web-control"
service:
  type: ClusterIP
  port: 80
  
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: local
  path: /
  hosts:
    - torrent.local
    - transmission.local

volumes:
  - name: "config"
    persistentVolumeClaim:
      claimName: "transmission-config" # PersistentVolumeClaim created earlier
  - name: "downloads"
    persistentVolumeClaim:
      claimName: "transmission-downloads" # PersistentVolumeClaim created earlier
#  - name: "dev-tun" # Needed for VPN
#    hostPath:
#      path: "/dev/net/tun"

volumeMounts:
  - name: "config"
    mountPath: "/data"
    subPath: "" # Path /mnt/ssd/media/configs/transmission-data where transmission writes the configuration
  - name: "downloads"
    mountPath: "/downloads/transmission"
    subPath: "" # Path /mnt/ssd/media/downloads/transmission where transmission downloads Torrents
#  - name: "dev-tun"
#    mountPath: "/dev/net/tun" # Needed for VPN
# Security context for container
securityContext:
  allowPrivilegeEscalation: true
  runAsUser: 0
  capabilities:
    add:
      - ALL

podSecurityContext:
  runAsUser: 0

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 1Gi


nodeSelector: {}

tolerations: []

affinity: {}


