apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: calibre-web-config
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-web-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: calibre-web-config
  local:
    path: /mnt/extra/calibre/web-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-main
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-config
  namespace: calibre
spec:
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  storageClassName: calibre-web-config
  resources:
    requests:
      storage: 1Gi
