apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: heimdall-config
provisioner: kubekrnetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: heimdall-config-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: "heimdall-config"
  local:
    path: /mnt/heimdall-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-main
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-config
  namespace: heimdall
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "heimdall-config"
  resources:
    requests:
      storage: 1Gi
