kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: palworld-backup
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: palworld-backup
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: palworld-backup
  local:
    path: /data/network/palworld-backup
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: palworld-backup
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: palworld-backup
  resources:
    requests:
      storage: 30Gi
