kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: palworld
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: palworld
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: palworld
  local:
    path: /data/local/palworld
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: palworld
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: palworld
  resources:
    requests:
      storage: 30Gi
