---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/gitrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab
  namespace: flux-system
spec:
  interval: 30m
  ref:
    branch: main
  url: https://github.com/stephenbarreca/homelab.git
  ignore: |
    # exclude all
    /*
    # include gitops dirs
    !/kubernetes