apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData: {}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc3uygu2npxjhz43rufgsad3wt7skff4792zlg7mk69uwm4stqpqjz9mll
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwL0VBK1JldUZIWXlPQ05H
            REdqVGhaRzdIdEhkRWl3anNQUlhRWGV1UzNJCllBRVVkSEFsbXdqeE1ZOGltUXBw
            cGFxTFF3RnlXT2dnYllDaTZNSXNhL00KLS0tIFdnN2c0c1lWR3lnYWxVRlBZSWpr
            cW5Vb3dIdFJFV0NkVFd6b2gxN01Gb2sKF7rFzFWvcMuFa39zzt8F17lJ6lcAdfZ6
            VXhjECsliqNHFEl8E2uJ0lDw2Bn8asnhyJFwI8ThlbJGxO1kqNfKrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-20T03:27:39Z"
    mac: ENC[AES256_GCM,data:9i/lCxoqlJlErI1YJSFlOYsmuEOOf0zKT4YKD5sS76Q5eueeeickVIwfw0elJhwWXiCiwGEmXeQBN97GDDBdUmQH9Yebu/cTpGb8bVQ0t+H4qELgpedz4SyoG8+t6/kq/i7oIAcki5SMr7Py0dquEGhNSmNNRr3JI55rlCCR0rI=,iv:hCYXUgfFblsXt+PB9cpuiVuaGdbgLVNYidydRVpXalM=,tag:kqv6MQkKEN6TkAfMBPAXcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
