---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./media-pvc/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./plex/ks.yaml
  - ./plex-image-cleanup/ks.yaml
  - ./plex-meta-manager/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./tautulli/ks.yaml
  # *Arr
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml