---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seerr
spec:
  chartRef:
    kind: OCIRepository
    name: seerr
  interval: 30m
  values:
    config:
      persistence:
        existingClaim: seerr-config

    extraEnv:
      - name: TZ
        value: America/New_York

    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: local
      hosts:
        - ingressClassName: traefik
          hosts:
            - host: seerr.stephenbarre.ca
              paths:
                - path: /
                  service:
                    identifier: app
                    port: http

    resources:
       limits:
         cpu: 100m
         memory: 128Mi
       requests:
         cpu: 100m
         memory: 128Mi
