---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lazy-librarian
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.3.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: flux-system

  values:
    controllers:
      main:
#        pod:
#          securityContext:
#            runAsUser: 0
#            runAsGroup: 568
#            runAsNonRoot: false
#            fsGroup: 568
#            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: linuxserver/lazylibrarian
              tag: version-e077f2b6
              pullPolicy: IfNotPresent
            env:
              # -- Set the container timezone
              TZ: America/New_York
              # -- Specify the user ID the application will run as
              PUID: "1000"
              # -- Specify the group ID the application will run as
              PGID: "1000"
              # -- for umask setting of Calibre, default if left unset is 022.
              UMASK_SET: "022"
#              DOCKER_MODS: linuxserver/mods:universal-calibre|linuxserver/mods:lazylibrarian-ffmpeg
              DOCKER_MODS: linuxserver/mods:universal-calibre
            probes:
              liveness:
                enabled: true
#                type: HTTP
#                path: /
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 300
            resources:
              requests:
                cpu: 14m
                memory: 1024M
              limits:
                cpu: 500m
                memory: 4024M
#            securityContext:
#              runAsUser: 568
#              runAsGroup: 568

    service:
      app:
        controller: main
        ports:
          http:
            port: &port_http 5299

    ingress:
      main:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: local
        className: traefik
        hosts:
          - host: lazy-librarian.stephenbarre.ca
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        type: persistentVolumeClaim
        existingClaim: lazy-librarian-config
        globalMounts:
          - path: /config
      books:
        type: persistentVolumeClaim
        existingClaim: books
        globalMounts:
          - path: /books
            subPath: books
            readOnly: False
          - path: /downloads
            subPath: downloads
            readOnly: False
      calibre:
        existingClaim: calibre-config-3
        globalMounts:
          - path: /calibre