kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: media
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
spec:
  capacity:
    storage: 25Ti
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media
  local:
    path: /data/network/media
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media
  resources:
    requests:
      storage: 25Ti
