apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minecraft-pokehaan-lite
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-pokehaan-lite
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  storageClassName: minecraft-pokehaan-lite
  local:
    path: /mnt/minecraft/modded/pokehaan-lite/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-main
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-pokehaan-lite
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: minecraft-pokehaan-lite
  resources:
    requests:
      storage: 1Gi

