# Chart: k8s-at-home/ombi
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  repository: linuxserver/ombi
  pullPolicy: Always
  tag: latest

strategy:
  type: Recreate

env: {}
  # TZ: UTC
  # PUID: 1001
  # PGID: 1001

podAnnotations:
  co.elastic.monitor/type: http
  co.elastic.monitor/urls: "http://${data.host}:{$data.port}/"
  co.elastic.monitor/schedule: "@every 10s"
  co.elastic.monitor/name: "Ombi"

# -- Configures service settings for the chart.
# @default -- See values.yaml
#service:
#  main:
#    ports:
#      http:
#        port: 80
#        targetPort: 3579
#    # loadBalancerIP: 192.168.1.203
    
ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  enabled: true
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure,local
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    traefik.ingress.kubernetes.io/router.tls.domains.0.main: ombi.stephenbarre.ca
  hosts:
    - host: "ombi.local"
      paths:
        - path: "/"
          backend:
            serviceName: "ombi"
            #servicePort: 80
    - host: "ombi.stephenbarre.ca"
      paths:
        - path: "/"
          backend:
            serviceName: "ombi"
            #servicePort: 80
persistence:
  config:
    enabled: true
    type: pvc
    existingClaim: ombi-config
    mountPath: /config

