repositories:
  - name: ks8-at-home-common
    url: https://library-charts.k8s-at-home.com
helmDefaults:
  skipDeps: true

templates:
  basic: &basic
    chart: ./{{`{{ .Release.Name }}`}}/{{`{{ .Release.Name }}`}}
    values:
      - ./{{`{{ .Release.Name }}`}}/values.yaml
    namespace: default

releases:
  - name: crashplan-pro
    recreatePods: true
    installed: true
    <<: *basic

