---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bjw-s-labs
  namespace: flux-system
spec:
  interval: 30m
  url: https://bjw-s-labs.github.io/helm-charts
  timeout: 3m