---
libraries:
  Movies:
    template_variables:
      use_separator: false
    collection_files:
      - file: config/movies_collections.yml
      - pmm: seasonal
        template_variables:
          collection_section: "010"
          visible_library: true
          visible_home: true
          visible_shared: true
      - pmm: universe
        template_variables:
          sort_title: "<<title>>"
      - pmm: based
        template_variables:
          sort_title: "<<title>>"
      - pmm: oscars
        template_variables:
          collection_section: "050"
          use_year_collections: false
          collection_order: release
      - pmm: cannes
        template_variables:
          collection_section: "051"
          use_year_collections: false
          collection_order: release
      - pmm: razzie
        template_variables:
          collection_section: "052"
          use_year_collections: false
          collection_order: release
      - pmm: studio
        template_variables:
          sort_title: "<<title>>"
          include:
            - A24
            - Blumhouse Productions
            - DreamWorks Studios
            - NEON
            - Pixar
            - Walt Disney Pictures
      - pmm: imdb
        template_variables:
          collection_section: "030"
          use_lowest: false
          use_popular: false
          radarr_add_missing_top: true
      - pmm: director
        template_variables:
          sort_title: "<<title>>"
          name_format: <<key_name>>
          data:
            depth: 3
            limit: 25
          include:
            - Akira Kurosawa
            - Alex Garland
            - Alfred Hitchcock
            - Christopher Nolan
            - Dario Argento
            - David Cronenberg
            - David Fincher
            - David Lynch
            - Denis Villeneuve
            - Guillermo del Toro
            - Ingmar Bergman
            - James Cameron
            - John Carpenter
            - Martin McDonagh
            - Martin Scorsese
            - Michael Mann
            - Paul Verhoeven
            - Park Chan-wook
            - Quentin Tarantino
            - Ridley Scott
            - Robert Eggers
            - Stanley Kubrick
            - Steven Spielberg
            - Tim Burton
            - Wes Anderson
            - Yorgos Lanthimos
          radarr_add_missing_Akira Kurosawa: true
          radarr_add_missing_Christopher Nolan: true
          radarr_add_missing_Denis Villeneuve: true
          radarr_add_missing_Guillermo del Toro: true
          radarr_add_missing_Ridley Scott: true
          radarr_add_missing_Wes Anderson: true
      - pmm: actor
        template_variables:
          sort_title: "<<title>>"
          data:
            depth: 5
            limit: 10
          include:
            - Arnold Schwarzenegger
            - Keanu Reeves
            - Jackie Chan
            - Pedro Pascal
            - Vin Diesel
      - pmm: writer
        template_variables:
          sort_title: "<<title>>"
          data:
            depth: 3
            limit: 5
          include:
            - Michael Crichton
            - Philip K. Dick
            - Stephen King
            - Tim Burton
          radarr_add_missing_Michael Crichton: true
          radarr_add_missing_Philip K. Dick: true
          radarr_add_missing_Stephen King: true
    overlay_files:
      - file: config/movies_overlays.yml
      - pmm: ribbon
        template_variables:
          use_rotten: false
          use_common: false
          use_cesar: false
          use_spirit: false
          use_berlinale: false
          use_venice: false
          use_metacritic: false
#      - pmm: ratings
#        template_variables:
#          horizontal_position: center
#          vertical_position: top
#          rating_alignment: horizontal
#          addon_position: left
#          rating1: critic
#          rating1_image: rt_tomato
#          rating2: audience
#          rating2_image: rt_popcorn
#          rating3: user
#          rating3_image: letterboxd
    remove_overlays: false
#    operations:
#      mass_user_rating_update: mdb_letterboxd
#      mass_poster_update:
#        source: plex
  TV Shows:
    collection_files:
      - file: config/tv_collections.yml
      - pmm: studio
        template_variables:
          include:
            - A24
            - Blumhouse Productions
            - DreamWorks Studios
            - NEON
            - Pixar
            - Walt Disney Pictures
      - pmm: actor
        template_variables:
          sort_title: "<<title>>"
          data:
            depth: 5
            limit: 5
          include:
            - Pedro Pascal
#    overlay_files:
#      - file: config/tv_overlays.yml
    remove_overlays: false
#    operations:
#      mass_poster_update:
#        source: plex

settings:
  cache: true
  cache_expiration: 60
  asset_directory:
  asset_folders: true
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: true
  download_url_assets: false
  show_missing_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  default_collection_order: None
  minimum_items: 1
  item_refresh_delay: 0
  delete_below_minimum: false
  delete_not_scheduled: false
  run_again_delay: 0
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: false
  show_missing: true
  save_report: false
  tvdb_language: default
  playlist_sync_to_users: all
  playlist_exclude_users: None
  playlist_report: true
  verify_ssl: true
  custom_repo: None
  check_nightly: false

mdblist:
  apikey: <<MDB_API_KEY>>
  cache_expiration: 60

omdb:
  apikey: <<OMDB_API_KEY>>
  cache_expiration: 60

plex:
  url: http://plex.media.svc.cluster.local:32400
  token: <<PLEX_API_KEY>>
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false

radarr:
  url: http://radarr:7878
  token: <<RADARR_API_KEY>>
  add_missing: false
  add_existing: false
  root_folder_path: /data/movies/movies
  monitor: true
  availability: released
  quality_profile: 1080p Preferred
  tag:
  search: false
  radarr_path:
  plex_path:
  upgrade_existing: false
  ignore_cache: false

sonarr:
  url: http://sonarr:8989
  token: <<SONARR_API_KEY>>
  add_missing: false
  add_existing: false
  root_folder_path: /data/tv/tv
  monitor: all
  quality_profile: ANY-1080p
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false
  sonarr_path:
  plex_path:
  upgrade_existing: false
  ignore_cache: false

tautulli:
  url: http://tautulli:8181
  apikey: <<TAUTULLI_API_KEY>>

tmdb:
  apikey: <<TMDB_API_KEY>>
  language: en
  cache_expiration: 60
  region:

trakt:
  client_id: <<TRAKT_CLIENT_ID>>
  client_secret: <<TRAKT_CLIENT_SECRET>>
  authorization:
    access_token: <<TRAKT_ACCESS_TOKEN>>
    token_type: Bearer
    expires_in: 7889237
    refresh_token: <<TRAKT_REFRESH_TOKEN>>
    scope: public
    created_at: 1709874033
