---
libraries:
  Movies:
    template_variables:
      use_separator: false
    collection_files:
      - file: config/movies_collections.yml
      - pmm: seasonal
        schedule: weekly(sunday)
        template_variables:
          collection_section: "010"
          visible_library: true
          visible_home: true
          visible_shared: true
      - pmm: universe
        schedule: weekly(monday)
        template_variables:
          sort_title: "<<title>>"
          radarr_add_missing_askew: true
          radarr_add_missing_avp: true
          radarr_add_missing_fast: true
          radarr_add_missing_mcu: true
          radarr_add_missing_mummy: true
          radarr_add_missing_rocky: true
          radarr_add_missing_star: true
          radarr_add_missing_trek: true
          radarr_add_missing_xmen: true
      - pmm: based
        schedule: all[monthly(5) monthly(20)]
        template_variables:
          sort_title: "<<title>>"
      - pmm: oscars
        schedule: monthly(1)
        template_variables:
          collection_section: "050"
          use_year_collections: false
          collection_order: release
          radarr_add_missing_best_picture: true
          radarr_add_missing_best_director: true
      - pmm: cannes
        schedule: monthly(2)
        template_variables:
          collection_section: "051"
          use_year_collections: false
          collection_order: release
          radarr_add_missing_palm: true
      - pmm: razzie
        schedule: monthly(3)
        template_variables:
          collection_section: "052"
          use_year_collections: false
          collection_order: release
          radarr_add_missing_golden: true
      - pmm: studio
        schedule: weekly(wednesday)
        template_variables:
          sort_title: "<<title>>"
          include:
            - A24
            - Blumhouse Productions
            - DreamWorks Studios
            - NEON
            - Pixar
            - Walt Disney Pictures
      - pmm: imdb
        schedule: weekly(thursday)
        template_variables:
          collection_section: "030"
          use_lowest: false
          use_popular: false
          radarr_add_missing_top: true
      - pmm: director
        schedule: weekly(friday)
        template_variables:
          sort_title: "<<title>>"
          name_format: "<<key_name>>"
          data:
            depth: 3
            limit: 25
          include:
            - Akira Kurosawa
            - Alex Garland
            - Alfred Hitchcock
            - Christopher Nolan
            - Dario Argento
            - David Cronenberg
            - David Fincher
            - David Lynch
            - Denis Villeneuve
            - Guillermo del Toro
            - Ingmar Bergman
            - James Cameron
            - John Carpenter
            - Martin McDonagh
            - Martin Scorsese
            - Michael Mann
            - Paul Verhoeven
            - Park Chan-wook
            - Quentin Tarantino
            - Ridley Scott
            - Robert Eggers
            - Stanley Kubrick
            - Steven Spielberg
            - Wes Anderson
            - Yorgos Lanthimos
          radarr_add_missing_Akira Kurosawa: true
          radarr_add_missing_Christopher Nolan: true
          radarr_add_missing_Denis Villeneuve: true
          radarr_add_missing_Guillermo del Toro: true
          radarr_add_missing_Ridley Scott: true
          radarr_add_missing_Wes Anderson: true
      - pmm: actor
        schedule: weekly(saturday)
        template_variables:
          sort_title: "<<title>>"
          name_format: "<<key_name>>"
          data:
            depth: 5
            limit: 10
          include:
            - Arnold Schwarzenegger
            - Keanu Reeves
            - Jackie Chan
            - Pedro Pascal
            - Vin Diesel
      - pmm: writer
        schedule: weekly(sunday)
        template_variables:
          sort_title: "<<title>>"
          name_format: "<<key_name>>"
          data:
            depth: 3
            limit: 5
          include:
            - Michael Crichton
            - Philip K. Dick
            - Stephen King
          radarr_add_missing_Michael Crichton: true
          radarr_add_missing_Philip K. Dick: true
          radarr_add_missing_Stephen King: true

    overlay_files:
      - file: config/movies_overlays.yml
      - pmm: ribbon
        template_variables:
          use_oscars: true
          use_oscars_director: true
          use_golden: false
          use_golden_director: false
          use_bafta: false
          use_cannes: true
          use_berlinale: false
          use_venice: false
          use_sundance: false
          use_emmys: false
          use_choice: false
          use_spirit: false
          use_cesar: false
          use_imdb: true
          use_rotten: false
          use_metacritic: false
          use_common: false
          use_razzie: false
    operations:
      - schedule: weekly(tuesday)
        mass_user_rating_update: mdb_letterboxd
    remove_overlays: false
    reapply_overlays: true
  TV Shows:
    collection_files:
      - file: config/tv_collections.yml
      - pmm: studio
        schedule: weekly(wednesday)
        template_variables:
          include:
            - A24
            - Blumhouse Productions
            - DreamWorks Studios
            - NEON
            - Pixar
            - Walt Disney Pictures
      - pmm: actor
        schedule: weekly(sunday)
        template_variables:
          sort_title: "<<title>>"
          data:
            depth: 5
            limit: 5
          include:
            - Pedro Pascal
#    overlay_files:
#      - file: config/tv_overlays.yml
    remove_overlays: false
#    operations:
#      mass_poster_update:
#        source: plex

playlist_files:
  - pmm: playlist
    schedule: all[monthly(1) monthly(15)]
    template_variables:
      use_arrow: false
      use_dcau: false
      use_dragonball: false
      use_pokemon: false
      use_clonewars: false

settings:
  cache: true
  cache_expiration: 60
  asset_directory:
  asset_folders: true
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: true
  download_url_assets: false
  show_missing_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  default_collection_order: None
  minimum_items: 1
  item_refresh_delay: 0
  delete_below_minimum: false
  delete_not_scheduled: false
  run_again_delay: 0
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: false
  show_missing: true
  save_report: false
  tvdb_language: default
  playlist_sync_to_users: all
  playlist_exclude_users: None
  playlist_report: true
  verify_ssl: true
  custom_repo: None
  check_nightly: false

mdblist:
  apikey: <<MDB_API_KEY>>
  cache_expiration: 60

omdb:
  apikey: <<OMDB_API_KEY>>
  cache_expiration: 60

plex:
  url: http://plex.media.svc.cluster.local:32400
  token: <<PLEX_API_KEY>>
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false

radarr:
  url: http://radarr:7878/radarr
  token: <<RADARR_API_KEY>>
  add_missing: false
  add_existing: false
  root_folder_path: /data/movies/movies
  monitor: true
  availability: released
  quality_profile: 1080p Preferred
  tag:
  search: false
  radarr_path:
  plex_path:
  upgrade_existing: false
  ignore_cache: false

sonarr:
  url: http://sonarr:8989/sonarr
  token: <<SONARR_API_KEY>>
  add_missing: false
  add_existing: false
  root_folder_path: /data/tv/tv
  monitor: all
  quality_profile: ANY-1080p
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false
  sonarr_path:
  plex_path:
  upgrade_existing: false
  ignore_cache: false

tautulli:
  url: http://tautulli:8181
  apikey: <<TAUTULLI_API_KEY>>

tmdb:
  apikey: <<TMDB_API_KEY>>
  language: en
  cache_expiration: 60
  region:

trakt:
  client_id: <<TRAKT_CLIENT_ID>>
  client_secret: <<TRAKT_CLIENT_SECRET>>
  authorization:
    access_token: <<TRAKT_ACCESS_TOKEN>>
    token_type: Bearer
    expires_in: 7889237
    refresh_token: <<TRAKT_REFRESH_TOKEN>>
    scope: public
    created_at: 1709874033
