templates:
  Chart:
    sort_title: "!!<<num>> <<collection_name>>"
    sync_mode: sync
collections:
  Movies Trending on Plex:
    template: { name: Chart, num: 1 }
    tautulli_popular:
      list_days: 14
      list_size: 30
      list_buffer: 30
    tautulli_watched:
      list_days: 14
      list_size: 30
      list_buffer: 30
    summary: Trending on Plex
    smart_label: plays.desc
    visible_library: true
    visible_home: true
    visible_shared: true
    cache_builders: 1

  Movies Trending Online:
    template: { name: Chart, num: 2 }
    trakt_chart:
      chart: trending
      limit: 25
    tmdb_trending_daily: 25
    tmdb_trending_weekly: 25
    summary: Trending across the internet
    smart_label: release.desc
    visible_library: true
    visible_home: true
    visible_shared: true
    cache_builders: 1

  Popular Movies This Year:
    template: { name: Chart, num: 3 }
    trakt_chart:
      chart: watched
      time_period: yearly
      limit: 25
    collection_order: custom
    radarr_add: false
    visible_library: true
    visible_home: true
    visible_shared: true
    cache_builders: 7

  Tim Burton:
    smart_filter:
      sort_by: release.desc
      any:
        writer: Tim Burton
        Director: Tim Burton
    url_poster: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-People-bw/master/T/Images/Tim%20Burton.jpg

  Maddy Favorites:
    name: "Maddy's Favorites"
    sort_title: "!!4 Maddy Favorites"
    sync_mode: sync
    letterboxd_list: https://letterboxd.com/slime_puppy/list/favorites/
    collection_order: title.asc

  Maddy Monthly Scavenger Hunt:
    name: "Maddy's Monthly Scavenger Hunt"
    sort_title: "!!5 Maddy Monthly Scavenger Hunt"
    sync_mode: sync
    letterboxd_list: https://letterboxd.com/slime_puppy/list/monthly-scavenger-hunt/share/gaPAcNO3zBXklqPV/
    collection_order: custom