---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
spec:
  chart:
    spec:
      chart: cilium
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      version: 1.15.2
  interval: 30m

  valuesFrom:
    - kind: ConfigMap
      name: cilium-values

  values:
    hubble:
      serviceMonitor:
        enabled: true

      dashboards:
        enabled: false
        label: grafana_dashboard
        namespace: monitoring
        labelValue: "1"
        annotations: {}

      relay:
        prometheus:
          serviceMonitor:
            enabled: false

      ui:
        ingress:
          enabled: true
          className: "internal-nginx"
          hosts:
            - &host hubble-main.stephenbarre.ca
          tls:
            - hosts:
                - *host

    prometheus:
      serviceMonitor:
        enabled: false

    operator:
      prometheus:
        serviceMonitor:
          enabled: false