repositories:
  - name: ks8-at-home
    url: https://k8s-at-home.com/charts/

helmDefaults:
  skipDeps: true

templates:
  kahData: &kahData
    chart: k8s-at-home/{{`{{ .Release.Name }}`}}
    namespace: plex
    values:
      - ./k8s_at_home/{{`{{ .Release.Name }}`}}.values.yaml
    valuesTemplate:
      - persistence:
          data:
            enabled: true
            type: hostPath
            hostPath: /mnt/plex
            accessMode: "ReadWriteMany"
            mountPath: /data
  kahNoData: &kahNoData
    chart: k8s-at-home/{{`{{ .Release.Name }}`}}
    namespace: plex
    values:
      - ./k8s_at_home/{{`{{ .Release.Name }}`}}.values.yaml
  basic: &basic
    chart: ./{{`{{ .Release.Name }}`}}/{{`{{ .Release.Name }}`}}
    values:
      - ./{{`{{ .Release.Name }}`}}/values.yaml
    namespace: plex

#helmfiles:
#  - path: k8s_at_home/helmfile.yaml
#  - path: transmission-openvpn/helmfile.yaml
#  - path: jackett/helmfile.yaml

releases:
  - name: jackett
    <<: *basic
  - name: ombi
    version: 9.4.0
    <<: *kahNoData    
  - name: plex
    version: 5.2.0
    <<: *kahData
  - name: radarr
    version: 12.2.0
    <<: *kahData
  - name: sonarr
    version: 12.2.0
    <<: *kahData
  - name: tautulli
    <<: *basic
  - name: transmission-openvpn
    recreatePods: true
    installed: true
    <<: *basic
  - name: qbittorrent-pia
    recreatePods: true
    installed: true
    <<: *basic

