apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gitea-data
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-data-nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: "gitea-data"
  nfs:
    server: "192.168.1.4"
    path: "/export/gitea/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data
  namespace: gitea
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "gitea-data"
  resources:
    requests:
      storage: 10Gi
 
