apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gitea-postgres
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-postgres-nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: "gitea-postgres"
  nfs:
    server: "192.168.1.4"
    path: "/mnt/user/gitea-postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-postgres
  namespace: gitea
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "gitea-postgres"
  resources:
    requests:
      storage: 5Gi
 
