apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: grafana-config
provisioner: kubekrnetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-config-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: "grafana-config"
  nfs:
    server: "192.168.1.4"
    path: "/mnt/user/grafana-config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-config
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "grafana-config"
  resources:
    requests:
      storage: 1Gi
