apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pihole-data
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-data-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: "pihole-data"
  nfs:
    server: "192.168.1.4"
    path: "/export/pihole"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-data
  namespace: pihole
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "pihole-data"
  resources:
    requests:
      storage: 1Gi
 
