# Default values for pihole.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "pihole/pihole"
  tag: latest
  pullPolicy: Always

serviceTCP:
  type: LoadBalancer
  loadBalancerIP: "192.168.1.240"
    # a fixed LoadBalancer IP
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
    co.elastic.monitor/0.type: http
    co.elastic.monitor/0.urls: "http://192.168.1.240/"
    co.elastic.monitor/0.schedule: "@every 10s"
    co.elastic.monitor/0.name: "PiHole Service Web"
    co.elastic.monitor/0.check.response.status: "200"
    co.elastic.monitor/1.type: tcp
    co.elastic.monitor/1.hosts: "192.168.1.240:80"
    co.elastic.monitor/1.schedule: "@every 10s"
    co.elastic.monitor/1.name: "PiHole Service DNS"
  externalTrafficPolicy: Local

serviceUDP:
  type: LoadBalancer
  loadBalancerIP: "192.168.1.240"
    # a fixed LoadBalancer IP
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  externalTrafficPolicy: Local

virtualHost: pi.hole

ingress:
  enabled: false

# Probes configuration
probes:
  # probes.liveness -- Configure the healthcheck for the ingress controller
  liveness:
    enabled: true
    initialDelaySeconds: 900
    failureThreshold: 10
    timeoutSeconds: 5
  readiness:
    enabled: true
    initialDelaySeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
   cpu: 300m
   memory: 512Mi
  requests:
   cpu: 30m
   memory: 256Mi

persistentVolumeClaim:
  # set to true to use pvc
  enabled: false
  # set to true to use you own pvc
  existingClaim: pihole-data
  # annotations: {}

  accessModes:
    - ReadWriteMany
  size: 1Gi
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"

nodeSelector: {}

tolerations:
  - key: "rpi"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - pihole
        topologyKey: "kubernetes.io/hostname"

# Administrator password when not using an existing secret (see below)
adminPassword: "7!Dn2#rxN%JUnQ"

# Use an existing secret for the admin password.
#admin:
#  existingSecret: "pihole-secret"
#  passwordKey: "password"

# extraEnvironmentVars is a list of extra enviroment variables to set for pihole to use
extraEnvVars: 
  TZ: "America/New_York"

# default upstream DNS servers to use
# DNS1: "192.168.1.250"
# DNS2: "192.168.1.250"

doh:
  # set to true to enabled DNS over HTTPs via cloudflared
  enabled: false
  name: "cloudflared"
  repository: "crazymax/cloudflared"
  tag: latest
  pullPolicy: IfNotPresent

dnsmasq:
  upstreamServers: []
  # Here you can add upstream dns servers with. All lines will be added to the
  # pihole dnsmasq configuration.
  # The format should be like:
  # - server=/foo.bar/192.168.178.10
  # - server=/bar.foo/192.168.178.11

  customDnsEntries:
  # Here you can add custom dns entries to override the
  # dns resolution with. All lines will be added to the
  # pihole dnsmasq configuration.
  # Hiemdall
  - address=/home.local/192.168.1.216
  - address=/heimdall.home.local/192.168.1.216
  - address=/www.home.local/192.168.1.216
  # Jackett
  - address=/jackett.home.local/192.168.1.201
  # Sonarr
  - address=/sonarr.home.local/192.168.1.202
  # Radarr
  - address=/radarr.home.local/192.168.1.203
  # Ombi
  - address=/ombi.home.local/192.168.1.204
  # Grafana
  - address=/grafana.home.local/192.168.1.205
  # Prometheus
  - address=/prometheus.home.local/192.168.1.206
  # Gitea
  - address=/git.home.local/192.168.1.210
  - address=/gitea.home.local/192.168.1.210
  # Magic-Mirror
  - address=/magic-mirror.home.local/192.168.1.211
  # Qbittorrent
  - address=/qbittorrent.home.local/192.168.1.215
  - address=/bittorrent.home.local/192.168.1.215
  - address=/torrent.home.local/192.168.1.215
  # Plex
  - rebind-domain-ok=/plex.direct/
  - address=/plex.home.local/192.168.1.241
  # Tautulli
  - address=/tautulli.home.local/192.168.1.243
  # Transmission
  - address=/transmission.home.local/192.168.1.245
  # Minecraft
  - address=/minecraft.home.local/192.168.1.220
  - address=/rcon.home.local/192.168.1.221
  # pihole
  - address=/pihole.home.local/192.168.1.240
  # Elasticsearch
  - address=/kibana.home.local/192.168.1.235

  additionalHostsEntries:
  # Dnsmasq reads the /etc/hosts file to resolve ips. You can add additional entries if you like
  - 192.168.1.4     tower
  - 192.168.1.55    k8s-main


adlists:
  - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  - https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts_without_controversies.txt
  - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
  - https://v.firebog.net/hosts/static/w3kbl.txt
  - https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt
  - https://someonewhocares.org/hosts/zero/hosts
  - https://raw.githubusercontent.com/vokins/yhosts/master/hosts
  - https://winhelp2002.mvps.org/hosts.txt
  - https://hosts.nfz.moe/basic/hosts
  - https://raw.githubusercontent.com/RooneyMcNibNug/pihole-stuff/master/SNAFU.txt
  - https://ssl.bblck.me/blacklists/hosts-file.txt
  - https://adaway.org/hosts.txt
  - https://v.firebog.net/hosts/AdguardDNS.txt
  - https://v.firebog.net/hosts/Admiral.txt
  - https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
  - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
  - https://v.firebog.net/hosts/Easylist.txt
  - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
  - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
  - https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
  - https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
  - https://v.firebog.net/hosts/Easyprivacy.txt
  - https://v.firebog.net/hosts/Prigent-Ads.txt
  - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
  - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
  - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
  - https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
  - https://hostfiles.frogeye.fr/multiparty-trackers-hosts.txt
  - https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
  - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt
  - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt
  - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/AmazonFireTV.txt
  - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
  - https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
  - https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
  - https://mirror1.malwaredomains.com/files/justdomains
  - https://v.firebog.net/hosts/Prigent-Crypto.txt
  - https://mirror.cedia.org.ec/malwaredomains/immortal_domains.txt
  - https://www.malwaredomainlist.com/hostslist/hosts.txt
  - https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
  - https://phishing.army/download/phishing_army_blocklist_extended.txt
  - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
  - https://v.firebog.net/hosts/Shalla-mal.txt
  - https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
  - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
  - https://urlhaus.abuse.ch/downloads/hostfile/
  - https://v.firebog.net/hosts/Prigent-Malware.txt
  - https://raw.githubusercontent.com/HorusTeknoloji/TR-PhishingList/master/url-lists.txt
whitelist:
  # If you want to provide whitelisted domains, add them here.
  - thepiratebay.org
  - api.vsee.com
  - services.gfe.nvidia.com
  - gfs.nvidia.com
  - sendgrid.net
  - 0.client-channel.google.com
  - 1drv.com
  - 2.android.pool.ntp.org
  - akamaihd.net
  - akamaitechnologies.com
  - akamaized.net
  - alluremedia.com.au
  - amazonaws.com
  - android.clients.google.com
  - api.ipify.org
  - api.rlje.net
  - app-api.ted.com
  - app.plex.tv
  - appleid.apple.com
  - apps.skype.com
  - appsbackup-pa.clients6.google.com
  - appsbackup-pa.googleapis.com
  - apt.sonarr.tv
  - aspnetcdn.com
  - attestation.xboxlive.com
  - ax.phobos.apple.com.edgesuite.net
  - brightcove.net
  - bufferapp.com
  - c.s-microsoft.com
  - cdn.cloudflare.net
  - cdn.embedly.com
  - cdn.optimizely.com
  - cdn.vidible.tv
  - cdn2.optimizely.com
  - cdn3.optimizely.com
  - cdnjs.cloudflare.com
  - cert.mgt.xboxlive.com
  - clientconfig.passport.net
  - clients1.google.com
  - clients2.google.com
  - clients3.google.com
  - clients4.google.com
  - clients5.google.com
  - clients6.google.com
  - cpms.spop10.ams.plex.bz
  - cpms35.spop10.ams.plex.bz
  - cse.google.com
  - ctldl.windowsupdate.com
  - d2c8v52ll5s99u.cloudfront.net
  - d2gatte9o95jao.cloudfront.net
  - dashboard.plex.tv
  - dataplicity.com
  - def-vef.xboxlive.com
  - delivery.vidible.tv
  - dev.virtualearth.net
  - device.auth.xboxlive.com
  - display.ugc.bazaarvoice.com
  - displaycatalog.mp.microsoft.com
  - dl.delivery.mp.microsoft.com
  - dl.dropbox.com
  - dl.dropboxusercontent.com
  - dns.msftncsi.com
  - download.sonarr.tv
  - drift.com
  - driftt.com
  - dynupdate.no-ip.com
  - ec-ns.sascdn.com
  - ecn.dev.virtualearth.net
  - edge.api.brightcove.com
  - eds.xboxlive.com
  - fonts.gstatic.com
  - forums.sonarr.tv
  - g.live.com
  - geo-prod.do.dsp.mp.microsoft.com
  - geo3.ggpht.com
  - giphy.com
  - github.com
  - github.io
  - googleapis.com
  - gravatar.com
  - gstatic.com
  - help.ui.xboxlive.com
  - hls.ted.com
  - i.s-microsoft.com
  - i.ytimg.com
  - i1.ytimg.com
  - imagesak.secureserver.net
  - img.vidible.tv
  - imgix.net
  - imgs.xkcd.com
  - instantmessaging-pa.googleapis.com
  - intercom.io
  - j.mp
  - jquery.com
  - jsdelivr.net
  - keystone.mwbsys.com
  - lastfm-img2.akamaized.net
  - licensing.xboxlive.com
  - live.com
  - login.aliexpress.com
  - login.live.com
  - login.microsoftonline.com
  - manifest.googlevideo.com
  - meta-db-worker02.pop.ric.plex.bz
  - meta.plex.bz
  - meta.plex.tv
  - microsoftonline.com
  - msftncsi.com
  - my.plexapp.com
  - nexusrules.officeapps.live.com
  - npr-news.streaming.adswizz.com
  - nine.plugins.plexapp.com
  - no-ip.com
  - node.plexapp.com
  - notify.xboxlive.com
  - ns1.dropbox.com
  - ns2.dropbox.com
  - o1.email.plex.tv
  - o2.sg0.plex.tv
  - ocsp.apple.com
  - office.com
  - office.net
  - office365.com
  - officeclient.microsoft.com
  - om.cbsi.com
  - onedrive.live.com
  - outlook.live.com
  - outlook.office365.com
  - pinterest.com
  - placehold.it
  - placeholdit.imgix.net
  - players.brightcove.net
  - pricelist.skype.com
  - products.office.com
  - proxy.plex.bz
  - proxy.plex.tv
  - proxy02.pop.ord.plex.bz
  - pubsub.plex.bz
  - pubsub.plex.tv
  - raw.githubusercontent.com
  - redirector.googlevideo.com
  - res.cloudinary.com
  - s.gateway.messenger.live.com
  - s.marketwatch.com
  - s.shopify.com
  - s.youtube.com
  - s.ytimg.com
  - s1.wp.com
  - s2.youtube.com
  - s3.amazonaws.com
  - sa.symcb.com
  - secure.avangate.com
  - secure.brightcove.com
  - secure.surveymonkey.com
  - services.sonarr.tv
  - sharepoint.com
  - skyhook.sonarr.tv
  - spclient.wg.spotify.com
  - ssl.p.jwpcdn.com
  - staging.plex.tv
  - status.plex.tv
  - t.co
  - t0.ssl.ak.dynamic.tiles.virtualearth.net
  - t0.ssl.ak.tiles.virtualearth.net
  - tawk.to
  - tedcdn.com
  - themoviedb.com
  - thetvdb.com
  - tinyurl.com
  - title.auth.xboxlive.com
  - title.mgt.xboxlive.com
  - traffic.libsyn.com
  - tvdb2.plex.tv
  - tvthemes.plexapp.com
  - twimg.com
  - twitter.com
  - ui.skype.com
  - v.shopify.com
  - video-stats.l.google.com
  - videos.vidible.tv
  - widget-cdn.rpxnow.com
  - wikipedia.org
  - win10.ipv6.microsoft.com
  - wordpress.com
  - wp.com
  - ws.audioscrobbler.com
  - www.dataplicity.com
  - www.googleapis.com
  - www.msftncsi.com
  - www.no-ip.com
  - www.youtube-nocookie.com
  - xbox.ipv6.microsoft.com
  - xboxexperiencesprod.experimentation.xboxlive.com
  - xflight.xboxlive.com
  - xkms.xboxlive.com
  - xsts.auth.xboxlive.com
  - youtu.be
  - youtube-nocookie.com
  - yt3.ggpht.com
  - adf.ly
  - www.adf.ly
  - bit.ly
  - www.bit.ly
  - goo.gl
  - ow.ly
  - www.ow.ly
  - amzn.to
  - amzn.com
  - ota-downloads.nvidia.com
blacklist: {}
  # If you want to have special domains blacklisted, add them here
  # - *.blackist.com

regex: {}
  # Add regular expression blacklist items
  # - (^|\.)facebook\.com$


webHttp: "80"
webHttps: "443"
hostNetwork: "false"
privileged: "false"
