---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      qbittorrent:
        annotations:
          configmap.reloader.stakater.com/reload: qbittorrent-scripts,qbittorrent-dnsdist
          secret.reloader.stakater.com/reload: qbittorrent-secret

        pod:
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            nameOverride: qbittorrent
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 4.6.4@sha256:85f185207a81ec03e84b8302db06f1694c533c99e0efdb2acf0316d554d332e3
            env:
              UMASK: "022"
              QBITTORRENT__PORT: &port 8080
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 49m
                memory: 1024Mi
              limits:
                memory: 8192Mi
            securityContext:
              runAsUser: 568
              runAsGroup: 568
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

          gluetun:
            image:
#              repository: ghcr.io/qdm12/gluetun
#              tag: v3.38.0
              repository: thrnz/docker-wireguard-pia
            env:
              LOC: ca_toronto
              LOCAL_NETWORK: 10.1.0.0/16,10.128.0.0/9
              PORT_FORWARDING: 1
              PORT_FILE: &port-file "/tmp/pia-shared/port.dat"
#              VPN_SERVICE_PROVIDER: private internet access
#              SERVER_REGIONS: CA Toronto
#              PORT_FORWARD_ONLY: true
#              PRIVATE_INTERNET_ACCESS_OPENVPN_ENCRYPTION_PRESET: strong
#              VPN_SERVICE_PROVIDER: custom
#              VPN_TYPE: wireguard
#              VPN_INTERFACE: wg0
#              VPN_ENDPOINT_PORT: 51820
#              VPN_PORT_FORWARDING_PROVIDER: private internet access
#              VPN_PORT_FORWARDING: on
#              FIREWALL_INPUT_PORTS: 8080
#              FIREWALL_OUTBOUND_SUBNETS: 10.1.0.0/16,10.128.0.0/9 # Allow access to k8s subnets
            envFrom:
              - secretRef:
                  name: qbittorrent-secret
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
              allowPrivilegeEscalation: false

          port-forward:
            dependsOn: gluetun
            image:
              repository: docker.io/snoringdragon/gluetun-qbittorrent-port-manager
              tag: "latest"
            env:
              - name: QBITTORRENT_SERVER
                value: localhost
              - name: QBITTORRENT_PORT
                value: *port
              - name: PORT_FORWARDED
                value: *port-file
#
#          port-forward:
#            image:
#              repository: ghcr.io/bjw-s/gluetun-qb-port-sync
#              tag: v0.0.1
#            env:
#              GLUETUN_CONTROL_SERVER_HOST: localhost
#              GLUETUN_CONTROL_SERVER_PORT: 8000
#              QBITTORRENT_HOST: localhost
#              QBITTORRENT_WEBUI_PORT: *port
#              CRON_ENABLED: true
#              CRON_SCHEDULE: "*/5 * * * *"
#              LOG_TIMESTAMP: false
#            securityContext:
#              runAsUser: 568
#              runAsGroup: 568
#              runAsNonRoot: true
#              allowPrivilegeEscalation: false
#              readOnlyRootFilesystem: false
#              capabilities:
#                drop:
#                  - ALL

    service:
      app:
        controller: qbittorrent
        ports:
          http:
            port: *port

    ingress:
      app:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: local
        className: traefik
        hosts:
          - host: qbittorrent.stephenbarre.ca
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config
        advancedMounts:
          qbittorrent:
            app:
              - path: /config
      movies:
        existingClaim: movies
        globalMounts:
          - path: /data/movies
      tv:
        existingClaim: tv
        globalMounts:
          - path: /data/tv

      port-data:
        type: emptyDir
        advancedMounts:
          qbittorrent:
            gluetun:
              - path: /tmp/pia-shared
            port-forward:
              - path: /tmp/pia-shared
                readOnly: true
