---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./qbittorrent-secret.sops.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: qbittorrent-scripts
    files:
      - ./scripts/port-forward.sh
generatorOptions:
  disableNameSuffixHash: true