apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-plex.stephenbarre.ca
  namespace: plex
spec:
  commonName: "plex.stephenbarre.ca"
  dnsNames:
    - "plex.stephenbarre.ca"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  secretName: tls-plex
