---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: calibre
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      calibre:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 0
#            runAsGroup: 568
#            runAsNonRoot: false
#            fsGroup: 568
#            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: linuxserver/calibre
              tag: 7.17.0
              pullPolicy: IfNotPresent
            env:
              # -- Set the container timezone
              TZ: America/New_York
              # -- Specify the user ID the application will run as
              PUID: "1001"
              # -- Specify the group ID the application will run as
              PGID: "1001"
              # -- for umask setting of Calibre, default if left unset is 022.
              UMASK_SET: "022"
              # -- Optionally pass cli start arguments to calibre.
              #CLI_ARGS:
              # -- HTTP Basic auth username, abc is default.
              #CUSTOM_USER:
              # -- HTTP Basic auth password, abc is default. If unset there will be no auth
              PASSWORD: ""
              TITLE: Calibre
              CUSTOM_PORT: &port 8080
              FM_HOME: &config-dir "/config"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 14m
                memory: 1024M
              limits:
                memory: 1024M


    service:
      app:
        controller: calibre
        ports:
          http:
            port: *port

    ingress:
      app:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: local
        className: traefik
        hosts:
          - host: calibre.stephenbarre.ca
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        existingClaim: calibre-config
        globalMounts:
          - path: *config-dir
      books:
        existingClaim: books
        globalMounts:
          - path: /books
