kind: Service
apiVersion: v1
metadata:
  name: &servicename unraid
spec:
  ports:
    - port: &port-ext 80
      # targetPort has to match the EndpointSlice port
      targetPort: &port-service 80
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: unraid-endpoint
  labels:
    kubernetes.io/service-name: *servicename
addressType: IPv4
ports:
  - appProtocol: http
    protocol: TCP
    port: *port-service
endpoints:
  - addresses:
      - "192.168.1.56"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: unraid-route-proxy
spec:
  entryPoints:
  - local
  routes:
  - kind: Rule
    match: Host(`unraid.stephenbarre.ca`) || Host(`tower.stephenbarre.ca`) || Host(`tower.local`)
    services:
    - kind: Service
      name: *servicename
      port: *port-ext

