apiVersion: v1
kind: Service
metadata:
  name: radarr-lb
  namespace: plex
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 7878
  selector:
    app: radarr
    release: radarr
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 192.168.1.203
