# Chart: k8s-at-home/ombi
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  repository: j4ym0/pia-qbittorrent
  pullPolicy: Always
  tag: latest

env:
  REGION: Canada
  USER:
  PASSWORD:


# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8888