kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: plex-local-config
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-local-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: plex-local-config
  local:
    path: /export/plex/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - snowhite
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-local-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "plex-local-config"
  resources:
    requests:
      storage: 50Gi
