kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc-plex-config
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-plex-config
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-plex-config
  local:
    path: /home/stephen/data/plex/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-main
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-plex-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-plex-config
  resources:
    requests:
      storage: 50Gi
