apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: calibre-web-automated-secret
stringData:
    HARDCOVER_TOKEN: ENC[AES256_GCM,data:AfJwZFyYdbeLsP3gA3DtKiw9jsC6WxdD2Tq0CpmJMbTjtEsapZOk/hWpZ58H6Dbtm+pV7t/H1QT77kxqRC60lccHJre84hCvhUP0F0f3gZbVx4PPJTAauxIXe30bH+5N9iJs0G3MvLAR493F3rKCpZP9zMcp44ynMEAHTXj8+ANALzcEj672rzg+cLU5X3XR/aWvvarqrvkdsE2wFZ41YUzF17hCejJPZ2n9Fdrm6YNUa+/zLdtavAaiptlN2XvWCbFPqb+s2ADOD4WXGXBki34xYX8n9NUga0W1x3DQoXnJi3pK7AIvFNqKJdijpYqs3PFPR0inrk0bMdBPDucvMonzGxrOcGXXQvQYXzKvin9A5i89MAzbBlq5ql5SWVlXKrWMKIQgOHvoYxTGlbyQ/5aGKxGJCUvCWQcltlmMv95tKwZKRmnFSeKtHP5nYl+Gm50cvOd6rOdwouyv4SZK1YEOxUF+IsKxvH+5Z2LmbcidGrTmD7t9OPChchy249hvrbZIDVdbdw6q4qC/4eTXzqh9qMVdbIM8eCogoW/kg7u6ww/J2V1GvV/w8GcbcxJMAIBfiNGAv7TSGGVWOMCLcNpX4AmdvxlPTEqFA9xqOMUUUIEvK6d/f9plBRD1a9+0n9kQ0fgf3JRdyQ15WV4lxS40gOpZVXQtAwxSIP0nwJ+/+FdHgodw+NAeYYEQvRIceTcN04Pe6UbBsim4UxoAnr0g,iv:HV4Ks3Wtz/9lKKUhAOwt66bp2RIDiwGCNzaYuyz2RW4=,tag:Mwryyr5Z/dyRYsnapp+b/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc3uygu2npxjhz43rufgsad3wt7skff4792zlg7mk69uwm4stqpqjz9mll
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SjJPai8wM2RLU2JrY0x5
            UmJ2cGNtZEtWMDY4a2tKekJZNVg2L0NBcVdRClNCUXhGVFpQMVErSG5JeUNrWVFt
            dHhXOTlzOEZqV3k1RVl4UUloTmwzN0UKLS0tIFdoRGx2TXR0QTNaaTFCNTZVa0JY
            U25YclNLY3dqdm5GejNwQnpHaWlEQTQK6VR07s7Q8pzLXazKl9IShZ8FBWoKJ3n5
            DTX9w43b90xOVJS0o772fU9zF+VELBMsTkhhbXU00oDYgpDOCWt16w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-08T01:43:36Z"
    mac: ENC[AES256_GCM,data:YI/8MSo6+JTOCVSu3D42BZVkBwR+nTASprlWjjNU/obRxCINNQZPMHb9lSLsD3RDisQ3nMxbJY6VUtiuVFLkL3tnUg3v15ZjyuxlB9hdNxzwbNj/NzhwfpX9kbI01Uxsd0aidTNKYFIaYmdulFff2f7VybyYtE7FfggEAZ7GYcA=,iv:iWlseOsYZsO7a58SgcooGD9I534eqZ51ViiCzPhcLAA=,tag:aD6U3INfxXiAK+cgbNTxCA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
