affinity: {}
claimToken: ""
deploymentAnnotations: {}
image:
  pullPolicy: IfNotPresent
  repository: plexinc/pms-docker
  tag: 1.16.0.1226-7eb2c8f6f
ingress:
  annotations: null
  enabled: false
  hosts:
  - chart-example.local
  tls: null
kubePlex:
  enabled: true
  image:
    pullPolicy: Always
    repository: quay.io/munnerz/kube-plex
    tag: latest
nodeSelector:
  beta.kubernetes.io/arch: amd64
persistence:
  config:
    accessMode: ReadWriteMany
    size: 20Gi
    storageClass: ""
  data:
    accessMode: ReadWriteMany
    size: 40Gi
    storageClass: ""
  extraData: []
  transcode:
    accessMode: ReadWriteMany
    size: 20Gi
    storageClass: ""
transcodeToMemory: false
plexGroup: "8675309"
plexUser: "1005"
podAnnotations: {}
proxy:
  enable: false
rbac:
  create: true
resources: {}
service:
  annotations: {}
  labels: {}
  loadBalancerIP: null
  port: 32400
  type: ClusterIP
timezone: Europe/London
tolerations: []
