kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: calibre-config
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-config-2
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: calibre-config
  local:
    path: /data/local/calibre
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-config-2
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: calibre-config
  resources:
    requests:
      storage: 100Gi
---