---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - movies.storage.yaml
  - plex-config.storage.yaml
  - prowlarr.storage.yaml
  - radarr.storage.yaml
  - sonarr.storage.yaml
  - tv.storage.yaml
