kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: qbittorrent-config
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: qbittorrent-config
  local:
    path: /data/local/qbittorrent
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: qbittorrent-config
  resources:
    requests:
      storage: 1Gi
---