apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server
  namespace: monitoring
spec:
  version: 7.13.2
  count: 1
  elasticsearchRef:
    name: elasticsearch
    namespace: monitoring
  kibanaRef:
    name: kibana
    namespace: monitoring