apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server
  namespace: monitoring
spec:
  version: 7.13.2
  count: 1
  elasticsearchRef:
    name: elasticsearch
    namespace: monitoring
  kibanaRef:
    name: kibana
    namespace: monitoring
  http:
    service:
      metadata:
        annotations:
          co.elastic.monitor/type: http
          co.elastic.monitor/hosts: "https://apm-server-apm-http.monitoring.svc:8200/"
          co.elastic.monitor/schedule: "@every 10s"
          co.elastic.monitor/ssl.verification_mode: "none"
          co.elastic.monitor/name: "APM Server"
