apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: heartbeat
  namespace: monitoring
spec:
  type: heartbeat
  version: 7.13.2
  elasticsearchRef:
    name: elasticsearch
  config:
    heartbeat:
      autodiscover:
        providers:
          # Autodiscover pods
          - type: kubernetes
            resource: pod
            scope: cluster
            node: ${NODE_NAME}
            hints:
              enabled: true


          # Autodiscover services
          - type: kubernetes
            resource: service
            scope: cluster
            node: ${NODE_NAME}
            include_annotations: ["monitor" ]
            hints:
              enabled: true

          # Autodiscover nodes
          - type: kubernetes
            resource: node
            node: ${NODE_NAME}
            scope: cluster
            templates:
              # Example, check SSH port of all cluster nodes:
              - config:
                  - hosts:
                      - ${data.host}:22
                    name: ${data.kubernetes.node.name}
                    schedule: '@every 10s'
                    timeout: 5s
                    type: tcp

      instrumentation:
        enabled: true
        environment: production
        hosts:
          - "http://apm-server-apm-http.monitoring.svc:8200"
        api_key: 0N41Syn50c6iEDWBY886O9wo

    processors:
      - add_host_metadata: {}
      - add_kubernetes_metadata: {}

  deployment:
    replicas: 1
    podTemplate:
      spec:
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
        containers:
          - name: heartbeat
            env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName