apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: monitoring
spec:
  version: 7.13.2
  count: 1
  http:
    service:
      metadata:
        annotations:
          co.elastic.monitor/type: http
          co.elastic.monitor/hosts: 192.168.1.235:5601
          co.elastic.monitor/schedule: "@every 10s"
          co.elastic.monitor/ssl.verification_mode: "none"
          co.elastic.monitor/name: "Kibana Service"
      spec:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.235
  elasticsearchRef:
    name: elasticsearch
    namespace: monitoring
  config:
    monitoring.ui.container.elasticsearch.enabled: true