apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: monitoring
spec:
  version: 7.13.2
  count: 1
  http:
    service:
      metadata:
        annotations:
          co.elastic.monitor/type: http
          co.elastic.monitor/hosts: "https://${data.host}:${data.port}"
          co.elastic.monitor/schedule: "@every 10s"
          co.elastic.monitor/ssl.verification_mode: "none"
          co.elastic.monitor/name: "Kibana Service"
      spec:
        ports:
          - name: https
            port: 443
            targetPort: 5601
    tls:
      selfSignedCertificate:
        subjectAltNames:
        - dns: kibana.local
  elasticsearchRef:
    name: elasticsearch
    namespace: monitoring
  config:
    monitoring.ui.container.elasticsearch.enabled: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kibana
  namespace: monitoring
spec:
  entryPoints:
    - local
    - traefik
    - websecure
  routes:
    - match: Host(`kibana.local`)
      kind: Rule
      services:
        - kind: Service
          name: kibana-kb-http
          port: 443
