apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: trakt-client-secret
stringData:
    id: ENC[AES256_GCM,data:7w9KPt7ew6e8BZMLqaJQZaMN2N6z487LmpxyO5mbRH0QV03BNpfOiOzgRnljivK0w4tY2GwWUABNa0tw5xPSiQ==,iv:WTwNwDKvpv7lAx3sk7u6LaEDOAEdJbIizH4nE7VFxiU=,tag:0uy9czcw/IAkGgjurfMmJw==,type:str]
    secret: ENC[AES256_GCM,data:b8Xyuu2z8C057azJCkF61LIi2bHUq81ZiQNPKobYbvN56YnYa2xqWD9/HI5jM21raElhVoxdss2E2jf2l6RTdg==,iv:y0X39bOHo54YwcQ+pKwGHUkgbBLTIbY87y6j1p2qlVM=,tag:cHR+Ub+8qBsDQLhTIq71Fg==,type:str]
    pin: ENC[AES256_GCM,data:L9UhPJm2sUA=,iv:xUa17b0Wd6qYCN949OW6r3SxeDvkMxA6vpR5IHhdL/Y=,tag:8LAZr0w9TTzIxACxPTSKlA==,type:str]
    access_token: ENC[AES256_GCM,data:Akc0ppwVW+6XcTkz6kRDmc8id7NEfbl1HGjUDg8rwz4QVXKU2RA+whyldTmtOj+7u3iHQBCgufv473moPr9Nog==,iv:WrZx/T7QDtstKTBjPCNuVeq8oqqZyBFnKqFAgWi3uM4=,tag:M2xiUZ71kklARNRXbisX2Q==,type:str]
    refresh_token: ENC[AES256_GCM,data:xcd2CGiQY+ENwtuEgXW5GbFv3tzJP7v+770KAvzUeQGUL82OIEEdoTn9WR6b+XgiwZcM62V599ICLGgHH8ogMg==,iv:o7rvX+EShKUiFRA2/c1cSd7OIriEtju+u/MOV0ssi3Q=,tag:RUNqz7Es6gcV/1q6DsbvVQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVVlyT2pnSHk1VWVjZFMz
            VFFUamtRd214WFlRV3J2aW1KaW9wRnVIaldVCmVpNkVJVUxyVk05ZHd3d0Z1Qzg4
            WDYwVFNvWllhdVBEYVNxcktJNTRJcG8KLS0tIFRmVmluengrOWZrTzhoUVNLem42
            NUNJTzZvbzVCVm5FWG00MDJhVGxMd1kKeD6QomLl0L+HprjygDpb7TIYa7twB3MD
            8P0nq2108O9MdjCzApY4Bvk8lt1qJkvYbLNekATMOUnUYjLKdAx+PQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pc3uygu2npxjhz43rufgsad3wt7skff4792zlg7mk69uwm4stqpqjz9mll
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-27T16:10:52Z"
    mac: ENC[AES256_GCM,data:brP9EpS9HFz3vZ1F16VhbJ49oqPWdEoOwPFhkV1DXmbhjUbU8BzIHZbtRqAV9Er8OncephueooSoI8u0LaXwTugS4ELml1SpAhVp6q8hdUFKFuJatyR3JHHh31JfuZv2CfqPO0fxFgiA2ol1ohDyHpy5hTAzMJXivNYY3Hfc+WM=,iv:xfuDX/ta2f0M2fuEj0M44/Hlx8CBtj4gNBdY8+m1KmY=,tag:099+sZNSfvE2oOFQAfNA9g==,type:str]
    version: 3.13.1
