apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: trakt-client-secret
stringData:
    id: ENC[AES256_GCM,data:Emh4pXqTicirmDxG8MITXwtsoZxN4+glqi0c6WU5srHnMLNTbr9MjG82NR6WDhzNn1HMcKcjGjsy8SLhN9BG3Q==,iv:cxnBYHL1fF7mCU653Kdj03qoBerzwCt0hIqlvmizA3Q=,tag:yij8+oI6hDcyLYDXUDSi+A==,type:str]
    secret: ENC[AES256_GCM,data:Gk48q1WJfCyL3MX/09I7YF2yMydh9ZEDjkA1jRJwfTJAXS7+2qd9BaCk1gEULNoQIsY6lF1eWrYL8wffpH6jug==,iv:/snokQ3owulGzoI9x+WKur1tvW8Fn/Bne3gSPUU+qvE=,tag:IPbLED9bwBxvdnlsNzsuRw==,type:str]
    pin: ENC[AES256_GCM,data:MK418KiW2Bg=,iv:DbtyxGU9MztVSS8aXG7dzKErB9Zk0oLz/zm7vUGEHSQ=,tag:KJ8tdYfZzjiNyblSxyKNig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVFJGYUN3YzJzYmlReFg4
            bFZqaW5TdmM5Sk5HbUxzU2x1cHo2ZFlIdkZvCjl6d2NTSS85ZnZBNzdpNEZnR2dB
            bWsxMWtEUjhZUSt3S05Ia2VjcXdsNnMKLS0tIEpRamtINERUQnQrOUhtK3NGVHA0
            NEtFM1hLWlRad2QrVm5zbm1yZ0NFL1EKVAtkygGt6V8fqD+6X78w1tyWkKXZ1WmM
            vHAHfPC7fRR64A1FozR2kfvFxk5fh+nQlWSvjG/7XKCPRMjElNUPhw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pc3uygu2npxjhz43rufgsad3wt7skff4792zlg7mk69uwm4stqpqjz9mll
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-27T15:10:15Z"
    mac: ENC[AES256_GCM,data:tUzpLw7pGCczmhLo6quOsCHLeWFRoeyz0R4g5g4T6y+QQayq2gO753U+bBFHe5X6kTWT+S+yYcQdFiEJkbl/uTFhsCMrtH4Hux27J0CCffe8RaeAeFFlAUQ3zMAy5cJim0QobwMsjtD1FODxCTH7G6zT6WS5OqKJFqSXpPFj5v0=,iv:DePUs33Ol6onfYlEKg99/MI18yAuWPw4x6lyP/m/hwk=,tag:rNnq/qFmmla6dPR3lJgsSA==,type:str]
    version: 3.13.1
