apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: trakt-client-secret
stringData:
    id: ENC[AES256_GCM,data:RglDr4n3eaqr9i/K9Q9O3iT5aMMT1Be97i5Dx/1blGWgsbsUln7SsrfV2e170zQTdhSAiaLKKD/jhZfltS0twQ==,iv:A+0QccQ8aACy8rdA3c9cssEUTRDH9NqyTMYkOn480Mc=,tag:JyrScqP/Ko7tldU8Cy+liw==,type:str]
    secret: ENC[AES256_GCM,data:xbV/xbJ1yQMySIMrXCYJhodju7BhhZE2are+iRF+VdRrgIXYpj1fMlNkW9LYT7jZ/VIY7+nvod0VNztnG+uYNA==,iv:N1Q98I6Ladk9HHtTTkKiZsUaqPIAxy3k/P61xG1cF9k=,tag:dZPwjZysPg4IZMot4yooHQ==,type:str]
    pin: ENC[AES256_GCM,data:VMSGUP2v4y0=,iv:nqVIUsgUUAL+yNo7oqjI3xNcCTqfbW4Tg9DagAJrFbI=,tag:cZvbkOKlnunPiwGLuY97PA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUckYvcGx5UDhGdUcwbVFF
            aGN2dDZzSi9heGRoYjBMZHlqSmxpN2QzZEM0CmdydHdoUUtkS0pTUUFMZEREamZV
            ZDdKamI0cVFxTVV0TkRGM3NkMGNjU2MKLS0tIHo5UTZDSWdvOERuRnhRUTJwK3Rz
            MnZ2SjNUUGhOR05NbnR1OG1LM25DemcKvIj8nwem9KR9XSKTHqwrTJk7Nzz/MJIs
            n+FS2ye+DxPi4xxeflTq4ZTHu9NPU8RrXVWgh5gybXY+fRC6QW3w4A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pc3uygu2npxjhz43rufgsad3wt7skff4792zlg7mk69uwm4stqpqjz9mll
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-27T15:24:07Z"
    mac: ENC[AES256_GCM,data:27P1IsYeGtXFQGuuqXx0z7vf4rZzRmm/VNn72eaW7FLqrkypGeUesYNz/R0Ohk4e8dMzetcvD/vIgNjsP8JSx8bN49qS824EsYFW0p8+fwHqhpAbmQFp2cRIPmWaW0/Xl5y3Szld3G71qOz2gcbxPmYTLhoF5SRwu3Q57S30zNg=,iv:YDdW0aKCUyCXOEwvGh41uvC5cpCBVf6ZbPk3ZoCigm0=,tag:k4Kq87hMbrfaAV3RKJksGA==,type:str]
    version: 3.13.1
