---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc-backblaze-config.yaml
  - pvc-backup-network.yaml
  - helmrelease.yaml
