kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: backup-network
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-network
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: backup-network
  local:
    path: /data/network
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-network
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: backup-network
  resources:
    requests:
      storage: 1Gi
