---

#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

# -- This is the default, you can also use requarks/wiki
image:
  # -- image repository
  repository: linuxserver/calibre
  # -- image tag
  tag: latest
  # -- image pull policy
  pullPolicy: Always

# -- environment variables. See [image docs](https://docs.linuxserver.io/images/docker-calibre#environment-variables-e) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: America/New_York
  # -- Specify the user ID the application will run as
  PUID: "1001"
  # -- Specify the group ID the application will run as
  PGID: "1001"
  # -- Username for the calibre gui
  GUAC_USER: fishfu
  # -- Password's md5 hash for the calibre gui
  GUAC_PASS: e66024904874fa14899e1f1a0835a60c
  # -- for umask setting of Calibre, default if left unset is 022.
  UMASK_SET: "022"
  # -- Optionally pass cli start arguments to calibre.
  CLI_ARGS:

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8080
  webserver:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: 192.168.1.215
    ports:
      webserver:
        enabled: true
        port: 8081
        protocol: TCP
        targetPort: 8081

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    type: pvc
    existingClaim: calibre-config
    mountPath: /config
  books:
    type: pvc
    existingClaim: books
    mountPath: /books