#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: linuxserver/calibre-web
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: latest

# -- environment variables. See more environment variables in the [calibre-web documentation](https://github.com/linuxserver/docker-calibre-web#parameters).
# @default -- See below
env:
  # -- Set the container timezone
  TZ: America/New_York
  # -- Specify the user ID the application will run as
  PUID: "1001"
  # -- Specify the group ID the application will run as
  PGID: "1001"
  # -- Adds the ability to perform ebook conversion
  DOCKER_MODS: linuxserver/calibre-web:calibre
# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8083

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: "calibre-web.local"
        paths:
          - path: "/"
            backend:
              serviceName: "calibre-web"
              servicePort: 80

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    type: pvc
    existingClaim: calibre-config
    mountPath: /config
  books:
    enabled: true
    type: pvc
    existingClaim: books
    mountPath: /books