#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: linuxserver/lazylibrarian
  # -- image tag
  tag: latest
  # -- image pull policy
  pullPolicy: Always

# -- environment variables.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: America/New_York
  # -- Specify the user ID the application will run as
  PUID: "1001"
  # -- Specify the group ID the application will run as
  PGID: "1001"
  ## Docker Mods are not actively tested and might not work as expected.
  DOCKER_MODS: linuxserver/calibre-web:calibre|linuxserver/mods:lazylibrarian-ffmpeg

podAnnotations:
  co.elastic.monitor/type: http
  co.elastic.monitor/urls: "http://${data.host}:${data.port}"
  co.elastic.monitor/schedule: "@every 10s"
  co.elastic.monitor/name: "LazyLibrarian"

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 5299

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: "lazylibrarian.local"
        paths:
          - path: "/"
            backend:
              serviceName: "lazylibrarian"
              servicePort: 80

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    type: pvc
    existingClaim: lazylibrarian
  media:
    enabled: true
    type: pvc
    existingClaim: calibre-config
    mountPath: /media
  books:
    enabled: true
    type: pvc
    existingClaim: books
probes:
  startup:
    enabled: true
    custom: true
    spec:
      httpGet:
        path: /
        port: 5299
      failureThreshold: 60
      periodSeconds: 10
