apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: magic-mirror-config
provisioner: kubekrnetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: magic-mirror-config-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: "magic-mirror-config"
  nfs:
    server: "192.168.1.4"
    path: "/export/magic-mirror/config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magic-mirror-config
  namespace: magic-mirror
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "magic-mirror-config"
  resources:
    requests:
      storage: 1Gi

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: magic-mirror-modules
provisioner: kubekrnetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: magic-mirror-modules-nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: "magic-mirror-modules"
  nfs:
    server: "192.168.1.4"
    path: "/export/magic-mirror/modules"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magic-mirror-modules
  namespace: magic-mirror
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "magic-mirror-modules"
  resources:
    requests:
      storage: 5Gi
