---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: 28.0.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 30m
  values:
    ports:
      traefik:
        port: 9000
        expose: false
        exposedPort: 9000
        protocol: TCP
        exposeInternal: false
      web:
        port: 8000
        expose: true
        exposedPort: 8080
        protocol: TCP
        exposeInternal: false
        redirectTo:
          port: websecure
      websecure:
        port: 8443
        expose: true
        exposedPort: 443
        protocol: TCP
        exposeInternal: false
        tls:
          enabled: true
          # this is the name of a TLSOption definition
          certResolver: "letsencrypt"
          domains:
            - main: "stephenbarre.ca"
              sans:
                - "*.stephenbarre.ca"
            - main: "autumnbarre.ca"
              sans:
                - "*.autumnbarre.ca"
      local:
        port: 7000
        expose: true
        exposedPort: 80
        protocol: TCP

      metrics:
        port: 9100
        expose: false
        exposedPort: 9100
        protocol: TCP

    certResolvers:
      letsencrypt:
        dnsChallenge:
          provider: cloudflare
        storage: /data/acme.json

    env:
      - name: CF_DNS_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: api-token

    deployment:
      initContainers:
        - name: volume-permissions
          image: busybox:latest
          command: [ "sh", "-c", "touch /data/acme.json; chmod -v 600 /data/acme.json" ]
          volumeMounts:
            - mountPath: /data
              name: data

    tlsOptions:
      default:
        sniStrict: false
        preferServerCipherSuites: true

    tlsStore:
      default:
        defaultCertificate:
          secretName: stephenbarre-ca-tls

    service:
      single: true
      type: LoadBalancer
      spec:
        externalTrafficPolicy: Local
        loadBalancerIP: 192.168.1.202

    ingressRoute:
      dashboard:
        enabled: true
        entryPoints:
          - traefik
          - local

    persistence:
      enabled: true
      storageClass: "microk8s-hostpath"