{{- if and .Values.persistence.data.enabled -}}
{{- if not .Values.persistence.data.persistentVolumeClaim -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "qbittorrent.fullname" . }}-data
  labels:
    app: {{ template "qbittorrent.fullname" . }}
    chart: {{ template "qbittorrent.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
  {{- if .Values.persistence.data.storageClass }}
  storageClass: {{ .Values.persistence.data.storageClass | quote }}
  {{- end }}
{{- end -}}
{{- end -}}
