# Chart: k8s-at-home/plex
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/ghcr.io/onedr0p/plex
  # -- image tag
  tag: rolling
  # -- image pull policy
  pullPolicy: Always

# -- environment variables. See [plex docs](https://support.plex.tv/articles/201105343-advanced-hidden-server-settings/) for more details.
# **NOTE:** Plex preference options are camelCase and CASE SENSITIVE!
# You can do horrible things to your Plex configuration if you are not careful
# @default -- See below
env:
  # -- Set the container timezone
  # TZ: America/New_York
  # NVIDIA_DRIVER_CAPABILITIES: "true"
  # ADVERTISE_IP:
  # ALLOWED_NETWORKS:
  PLEX_CLAIM: "claim-ayLynSaVr5kNvypzRxSK"
  PLEX_UID: "1005"
  PLEX_GID: "8675309"
  PMS_INTERNAL_ADDRESS: "http://plex:32400"
  # PLEX_PREFERENCE_1: "FriendlyName=plex-kubernetes"
  # PLEX_PREFERENCE_2: "EnableIPv6=0"
  # PLEX_PREFERENCE_3: "logDebug=0"
  # PLEX_PREFERENCE_4: "DisableTLSv1_0=1"
  # PLEX_PREFERENCE_5: "LanNetworksBandwidth=xxx.xxx.xxx.0/18\,xxx.xxx.xxx.0/24\,xxx.xxx.xxx.0/24"
  # PLEX_PREFERENCE_6: "TranscoderQuality=2"
  # PLEX_PREFERENCE_7: "TreatWanIpAsLocal=0"
  # PLEX_PREFERENCE_8: "TranscoderH264BackgroundPreset=fast"

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    primary: true
    type: LoadBalancer
    # loadBalancerIP: 192.168.1.241
    externalTrafficPolicy: Local
    annotations:
      co.elastic.monitor/0.type: http
      co.elastic.monitor/0.urls: "http://${data.host}:${data.port}/web"
      co.elastic.monitor/0.schedule: "@every 10s"
      co.elastic.monitor/0.name: "Plex"
      co.elastic.monitor/1.type: http
      co.elastic.monitor/1.urls: "https://plex.stephenbarre.ca:443/web"
      co.elastic.monitor/1.schedule: "@every 10s"
      co.elastic.monitor/1.name: "plex.stephenbarre.ca"
      # co.elastic.monitor/check.response.status: "200"
    ports:
      http:
        enabled: true
        port: 80
        targetPort: 32400
  dnla-tcp:
    enabled: false
    externalTrafficPolicy: Local
  dnla-udp:
    enabled: false
    externalTrafficPolicy: Local

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure,local
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
      traefik.ingress.kubernetes.io/router.tls.domains.0.main: plex.stephenbarre.ca
    hosts:
      - host: "plex.stephenbarre.ca"
        paths:
          - path: "/"
            backend:
              serviceName: "plex"

# -- Enable devices to be discoverable
hostNetwork: true

probes:
  liveness:
    enabled: true
    ## Set this to true if you wish to specify your own livenessProbe
    custom: true
    ## The spec field contains the values for the default livenessProbe.
    ## If you selected custom: true, this field holds the definition of the livenessProbe.
    spec:
      httpGet:
        path: /web
        port: 32400
      failureThreshold: 10
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
  readiness:
    enabled: true
    ## Set this to true if you wish to specify your own livenessProbe
    custom: true
    ## The spec field contains the values for the default livenessProbe.
    ## If you selected custom: true, this field holds the definition of the livenessProbe.
    spec:
      httpGet:
        path: /web
        port: 32400
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
  startup:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    type: pvc
    existingClaim: plex-config
    mountPath: /config
#  data:
#    enabled: true
#    type: hostPath
#    hostPath: /mnt/plex
#    # existingClaim: plex-combo
#    mountPath: /data
#    accessMode: ReadWriteMany
#    size: 7Ti
  transcode:
    enabled: true
    type: emptyDir
    medium: Memory
    mountPath: /transcode


# -- Configure the Security Context for the Pod
podSecurityContext:
  runAsUser: 0
  #runAsUser: 1005
  #runAsGroup: 8675309
  # fsGroup: 568
  # # Hardware acceleration using an Intel iGPU w/ QuickSync
  # # These IDs below should be matched to your `video` and `render` group on the host
  # # To obtain those IDs run the following grep statement on the host:
  # # $ cat /etc/group | grep "video\|render"
  # # video:x:44:
  # # render:x:109:
  # supplementalGroups:
  # - 44
  # - 109

# -- Configure the resource requests and/or limits for the Pod
resources:
  requests:
    cpu: 0.5
    memory: 1Gi
  limits:
    cpu: 13
    memory: 8Gi
    nvidia.com/gpu: 1

