---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: plex
spec:
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      plex:

        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          hostNetwork: true
          nodeSelector:
            nvidia.com/gpu.present: "true"
          securityContext:
            runAsUser: 0
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 44
              - 109
              - 65542 # gladius:external-services

        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/plex
              tag: rolling
              pullPolicy: Always
            env:
              #PLEX_ADVERTISE_URL: https://10.45.0.20:32400,https://plex.bjw-s.dev:443
              #PLEX_NO_AUTH_NETWORKS: 10.244.0.0/16
              PLEX_UID: "1005"
              PLEX_GID: "8675309"
              PMS_INTERNAL_ADDRESS: "http://plex:32400"
              TZ: America/New_York
            envFrom:
              - secretRef:
                  name: plex-secrets
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 100m
                nvidia.com/gpu: 1
                memory: 9248M
              limits:
                nvidia.com/gpu: 1
                memory: 9248M

    service:
      app:
        controller: plex
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
          http:
            port: 32400

    ingress:
      app:
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        className: "external-nginx"
        hosts:
          - host: &hostName plex.stephenbarre.ca
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *hostName

    persistence:
      config:
        existingClaim: plex-config
        advancedMounts:
          plex:
            app:
              - path: /config
      movies:
        existingClaim: movies
        advancedMounts:
          plex:
            app:
              - path: /data/movies
      tv:
        existingClaim: tv
        advancedMounts:
          plex:
            app:
              - path: /data/tv
      logs:
        type: emptyDir
        advancedMounts:
          plex:
            app:
              - path: /config/Library/Application Support/Plex Media Server/Logs
      transcode:
        type: emptyDir
        medium: Memory
        advancedMounts:
          plex:
            app:
              - path: /transcode
