apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: plex-secrets
stringData:
    PLEX_CLAIM: ENC[AES256_GCM,data:J9aewhqSDQQgcsCURhOFOB3gyn8BJMJT2X4=,iv:j8hj4050ovK7glr5QHnVnKSG7ik1cr+Mr6rW+pb3Ikk=,tag:Bu9HAFKq0pHVy1ohkv+VbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc3uygu2npxjhz43rufgsad3wt7skff4792zlg7mk69uwm4stqpqjz9mll
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHV0Y3Mm9ldHNKWFkzODlW
            V0dpQ1ROWVpoTWtYV1B6K00zNVIwUjhzMUNBClpOcGU5blpXT2pMd0FDUDVEMnRt
            dDFiSys0K0hLN2o0NFVxYXpWYjBzU1EKLS0tIDVjTW1KcWRFT3Y0NVIvb0g4TmhH
            b0Z4REE1ckcrTFA5SzVPbzhmKzVUYTQKdrR0XXHCFTKVUikQw46gTfehl3YabmQj
            1LVF8myEEwxxSpfPEdFhrpevEDPWSnGZV1YqgEacfP1a86DKsMf8WQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-21T21:23:22Z"
    mac: ENC[AES256_GCM,data:VMOLBGMImWuleFIPRf0JEpssKxCm9gqx92jMisk/gd0BADlV8EjpVJlOC+5k57r3QvHUxJBHosk16CzmgRDogazxdB503rfHbkCqp2yo6rst0S86SrLe5AMplmBzzFHp/GowjglNCfVIOlX16jN98zYPCp7b2UZqoq5sYbc9D0Y=,iv:V24SgA3k1gH3gU3A3di0IN3MK/yXVaBn+dLRaFwyReQ=,tag:t88fa2CcPxbZRFjA0gCtTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
