apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ombi-config
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ombi-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  storageClassName: "ombi-config"
  local:
    path: /mnt/ombi-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-main
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ombi-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  storageClassName: "ombi-config"
  resources:
    requests:
      storage: 1Gi
