apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- ./repositories
- ./vars
patches:
  - patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: not-used
        namespace: not-used
      spec:
        decryption:
          provider: sops
          secretRef:
            name: sops-age
        postBuild:
          substituteFrom:
            - kind: ConfigMap
              name: cluster-settings
            - kind: Secret
              name: cluster-secrets
    target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
      labelSelector: substitution.flux.home.arpa/disabled notin (true)