apiVersion: v2
name: k8s_at_home_common
description: Copy of the archived Function library for k8s-at-home charts
type: library
version: 4.5.2
kubeVersion: ">=1.16.0-0"
keywords:
  - k8s-at-home
  - common
home: https://github.com/k8s-at-home/library-charts/tree/main/stable/common
