apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jackett-config
provisioner: kubekrnetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jackett-downloads
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jackett-config-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: "jackett-config"
  nfs:
    server: "192.168.1.4"
    path: "/mnt/user/jackett-config"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jackett-downloads-nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: "jackett-downloads"
  nfs:
    server: "192.168.1.4"
    path: "/mnt/user/jackett-downloads"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "jackett-config"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-downloads
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "jackett-downloads"
  resources:
    requests:
      storage: 10Gi
