
replicaCount: 1

image:
  repository: linuxserver/jackett
  tag: latest
  pullPolicy: Always

env:
  - name: VPN_ENABLED
    value: "yes" # Enable Jackett over VPN
#  - name: VPN_USERNAME
#    valueFrom:
#      secretKeyRef: # Reference to the secret | openvpn.username
#        name: "openvpn"
#        key: "username"
#  - name: VPN_PASSWORD
#    valueFrom:
#      secretKeyRef: # Reference to the secret | openvpn.password
#        name: "openvpn"
#        key: "password"
  - name: LAN_NETWORK
    value: "192.168.0.0/24"
  - name: CREATE_TUN_DEVICE
    value: "true" # Needed for VPN
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

#service:
#  type: LoadBalancer
#  port: 80
#   loadBalancerIP: 192.168.1.201

ingress:
  enabled: true
  ingressClassName: traefik
  path: /
  hosts:
    - jackett.local

volumes:
  - name: "config"
    persistentVolumeClaim:
      claimName: "jackett-config" # PersistentVolumeClaim created earlier
  - name: "downloads"
    persistentVolumeClaim:
      claimName: "jackett-downloads" # PersistentVolumeClaim created earlier
  - name: "dev-tun"  # Needed for VPN
    hostPath:
      path: "/dev/net/tun"

volumeMounts:
  - name: "config"
    mountPath: "/config"
    subPath: "" # Path  where jackett writes the configuration
  - name: "downloads"
    mountPath: "/downloads"
    subPath: "" # Path ???


resources:
  requests:
    memory: 256Mi
    cpu: 0.1
  limits:
    memory: 512Mi
    cpu: 0.5

securityContext:
  capabilities: # Needed for VPN
    add:
      - NET_ADMIN

nodeSelector: {}

tolerations: []

affinity: {}

