replicaCount: 1

image:
  repository: linuxserver/sonarr
  tag: preview
  pullPolicy: Always

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

apiKey: "b4edc371290a4864a54dddf452a62cf8"

service:
  type: LoadBalancer
  port: 80
  loadBalancerIP: 192.168.1.202

volumes:
  - name: config
    persistentVolumeClaim:
      claimName: sonarr-config
  - name: downloads
    persistentVolumeClaim:
      claimName: qbittorrent-downloads
  - name: plex-data
    persistentVolumeClaim:
      claimName: plex-nfs-data
volumeMounts:
  - name: config
    mountPath: "/config"
    subPath: ""
  - name: downloads
    mountPath: "/downloads"
    subPath: ""
  - name: plex-data
    mountPath: "/tv"
    subPath: "tv/"

resources:
  requests:
    memory: 256Mi
    cpu: 0.1
  limits:
    memory: 512Mi
    cpu: 1.0

nodeSelector: {}

tolerations: []

affinity: {}

