replicaCount: 1

image:
  repository: linuxserver/sonarr
  tag: latest
  pullPolicy: IfNotPresent

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

service:
  type: ClusterIP
  port: 80

volumes:
  - name: config
    persistentVolumeClaim:
      claimName: sonarr-config
  - name: downloads
    persistentVolumeClaim:
      claimName: qbittorrent-downloads
  - name: plex-data
    persistentVolumeClaim:
      claimName: plex-nfs-data

volumeMounts:
  - name: config
    mountPath: "/config"
    subPath: ""
  - name: downloads
    mountPath: "/downloads"
    subPath: ""
  - name: plex-data
    mountPath: "/tv"
    subPath: "tv/"

resources:
  requests:
    memory: 256Mi
    cpu: 0.1
  limits:
    memory: 512Mi
    cpu: 1.0

nodeSelector: {}

tolerations: []

affinity: {}

