replicaCount: 1

image:
  repository: linuxserver/sonarr
  tag: latest
  pullPolicy: Always

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

apiKey: "b4edc371290a4864a54dddf452a62cf8"

service:
  type: LoadBalancer
  port: 80
  loadBalancerIP: 192.168.1.202

volumes:
  - name: config
    persistentVolumeClaim:
      claimName: sonarr-config
  - name: downloads
    persistentVolumeClaim:
      claimName: transmission-downloads
  - name: plex-data
    persistentVolumeClaim:
      claimName: pvc-plex-tv
volumeMounts:
  - name: config
    mountPath: "/config"
    subPath: ""
  - name: downloads
    mountPath: "/downloads/transmission"
    subPath: ""
  - name: plex-data
    mountPath: "/tv"
    subPath: ""

resources:
  requests:
    memory: 1Gi
    cpu: 0.1
  limits:
    memory: 2Gi
    cpu: 0.3

nodeSelector: {}

tolerations: []

affinity: {}

