apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  version: 8.1.3
  http:
    service:
      metadata:
        annotations:
          co.elastic.monitor/type: http
          co.elastic.monitor/hosts: "https://elasticsearch-es-http.monitoring.svc:9200/_cat/health"
          co.elastic.monitor/username: "elastic"
          co.elastic.monitor/password: "g8fj58E1E18Q6l4khp7btZy7"
          co.elastic.monitor/schedule: "@every 10s"
          co.elastic.monitor/ssl.verification_mode: "none"
          co.elastic.monitor/name: "Elasticsearch Service"
      spec:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.230
    tls:
      selfSignedCertificate:
        subjectAltNames:
        - dns: es.local
  nodeSets:
  - name: main
    count: 1
    config:
      path:
        repo:
          - /usr/share/elasticsearch/snapshots
      # node.store.allow_mmap: false
#    volumeClaimTemplates:
#      - metadata:
#          name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
#        spec:
#          accessModes:
#            - ReadWriteOnce
#          resources:
#            requests:
#              storage: 1Gi
#          storageClassName: standard
    podTemplate:
      spec:
        containers:
          - name: elasticsearch
            volumeMounts:
              - name: backup
                mountPath: /usr/share/elasticsearch/snapshots
            resources:
              limits:
                memory: 8Gi
                cpu: 1
              requests:
                memory: 8Gi
                cpu: 200m
        volumes:
          - name: backup
            hostPath:
              path: /mnt/extra/es-backup
              type: Directory

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  entryPoints:
    - local
    - traefik
    - websecure
  routes:
    - match: Host(`elasticsearch.local`)
      kind: Rule
      services:
        - kind: Service
          name: elasticsearch-es-http
          port: 9200
