---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - plex-meta-manager-config.storage.yaml
  - omdb-secret.sops.yaml
  - tmdb-secret.sops.yaml
  - trakt-secret.sops.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: plex-meta-manager-configmap
    files:
      - ./config/config.yml
      - ./config/movies_collections.yml
      - ./config/movies_overlays.yml
      - ./config/tv_collections.yml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
