apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: mdb-secret
stringData:
    api-key: ENC[AES256_GCM,data:31uY+mxYbP+sFjaZ8AhL3+GPLyZ/3Fpo1g==,iv:wBJbefKoGLUG43evyHMF4g0I7I1V3fDZ1sffmgDDZug=,tag:z3Rok0U6gEGhx/xxXhbOkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc3uygu2npxjhz43rufgsad3wt7skff4792zlg7mk69uwm4stqpqjz9mll
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cVpheHFtY0dINmk4b1NX
            emQ5blowRk1HYUhiYnlnL0JxU1pNZWlIc1ZnCnJhUEpKQ0d0anRvVG1oUFhITzYx
            Z3pCZHJZaFZBaHdFOC9sZHVVMXpobWcKLS0tIHA3MEZpMWNEa1BTa1MxbmtoY2dX
            NXF1TkxROE1PZzczektRUXhtazB3RmsKGk6MBAClS/d01diYH9TNRIsluieyGQmA
            lan9syXL+PvyYvvBr094BXa1xWgXBElZPix/RAPAfP5xvekzISQgjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-23T04:07:36Z"
    mac: ENC[AES256_GCM,data:qczk1taGpUi1OWprbYjMeLEONuDKwQxDI6zoFVixMo2JuJHCj/X2yVL7oYgzM3OEM4TyFaFNdaqlqtXeSS6+/vtm4ywcfG+xluNL+NUK4efyi1IQKXixiJwYuu370+XkoDJ+ZIk9Lp6sUH6b39O/2OhZLa8eBuJ/T2137xRH/kY=,iv:u++GV6Ic+nuoudANWKj0fMh3AYd2fAhHpxFadF5DyVc=,tag:xGi1dYiHlWNw+ZHtY1dhfA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
