kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: plex-meta-manager-config
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-meta-manager-config
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: plex-meta-manager-config
  local:
    path: /data/network/media/movies/plex-meta-manager
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-meta-manager-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: plex-meta-manager-config
  resources:
    requests:
      storage: 10Mi
