apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: trakt-client-secret
stringData:
    id: ENC[AES256_GCM,data:1BH+70Gl03Dpf1UbmVpsVXuufPEtuLemDbu8/QL+6Of16bjaOHpTr1Dt0R0uA8O4v030+MDeM90CiimAmxGzpg==,iv:HrEMv7nvgOcxPaKG6b1QBsS4MiTsQcWRIy6yb3KQ+PY=,tag:9uIt8+17iM3MA27M7Y5Efg==,type:str]
    secret: ENC[AES256_GCM,data:AQ+nnG1GrInwdgzf0Tioqid5tK2myXuLBzddM0yQhSPPtgGYyYPeGuSUKn+wk67luPeHYvO7W0cJr0VceNp0BA==,iv:YOF0nWZ+/XD0llRfQpAX900FR8AcgQU3DfsV4l8NQiM=,tag:oPkNhN5J/eHlkJW2sNoi0g==,type:str]
    access_token: ENC[AES256_GCM,data:4GfXzo9rowZKyH9rnqtj6rbntvawDc8FfEgOcdgmPZr9tB6FkparVCHRhgmU8FPrKuWiql7+6p7qeUnbzzsvQQ==,iv:0Ya+wSLaVZ76BI/tsD2zK9OvVZ9cFwBgQ6synjrdQeY=,tag:R6Qm87y+xfYKATAhjVYShA==,type:str]
    refresh_token: ENC[AES256_GCM,data:wDPg+QyTkv2HW2/jx/YSGM6JN8dok4uqC+TYfe/nqk4Gyi3KUdxMZT0dqlkG8+Pmoh5W4/CKz56CoHIxyASZqw==,iv:89mUvMfMOLPadrMPJLPXmKbRXiYmsFDym64yvZbB/jw=,tag:2OYnQBLSfQQVyib5D1ESmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc3uygu2npxjhz43rufgsad3wt7skff4792zlg7mk69uwm4stqpqjz9mll
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbWQrRmdmVlJxTysrSnR6
            MkxkbGtTOEQvT1dRcDQ0RW55bWZNV3JuNERnClhZdzE0alJQZGZrVlRoVXJKb2R1
            VUM5eDVYT21MT3pGbnRuc1VrSmdjdjQKLS0tIFhtRlFOZFdXak1lMzN3TzM1Rksr
            UEpSWTJGb2Y2d0QxSUlrd1pLbCtQeEUKdxZTamW3BzDbq6fVXsQBdx8y/u6gkn5Q
            2HfgBlRpXiWIeh8v/Bg8ICA7E8Fld0BjCEnxBjyGDYzCAdYfKKqmHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T13:29:45Z"
    mac: ENC[AES256_GCM,data:7jPwuAYWowq1YRD8z/1w1+jzoh4vcUVj9yB4X+L4iaN5MUM0CD+xRuNVestcTnsTQv6JCGekivs4vB+XcrtUN5pnwjOZtanGliPnTUD4xmaopq0FN8zaCGE9W+d3VHqVDmklSfrp6ZGFd/ZxhhU2Dd8ZYNKxPKlfeqqQwlM4RJU=,iv:55Azd6dZ1vIFWtjlcqF0YkvTVdI2itOSksu3PNMpQuA=,tag:8AEXfxg6/SZuQtIit+VDkw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
