apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: trakt-client-secret
stringData:
    id: ENC[AES256_GCM,data:svBfXe0AaAncWzivuqVvB9tV2D0vjPKUPiQFkeWxQk4cMnnG0jNUUJsxHI4DcM6gAJ4BZEcb5fr4PfZCOGDsFA==,iv:jE4crdpSREkrantgcwPFXqbhQ2U6Zsv+wIDnz0/x1vY=,tag:5iwYxsFkgXojWhH6zkxA1A==,type:str]
    secret: ENC[AES256_GCM,data:iSYxcUFZYlCRmjVJYU/Hl/6vuwqvfllDjPXPOafnbOKMilzXESR8c4B1WrsVR0+HcKjGH0AE24QSRNrVxNxn9Q==,iv:cKRxrOHd/zR1Ys+1VVrAef1jgOjNONY/oqEslu3kYNg=,tag:WXfLtgCSps1NB9Q+YhEwSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc3uygu2npxjhz43rufgsad3wt7skff4792zlg7mk69uwm4stqpqjz9mll
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZY1M5eWxuckEzbWVZYWls
            TzlxaVhTL3hoK3RhSGQ4aU1kUllxQUk0Y0QwCnFESlY1Vk52bVNDOTF5Q3R2cUNW
            RHZSeER5cllOZFdld2VuWEMwZU5jS00KLS0tIDlMRjVUTEcyaGFaelUzV0RnODlH
            S1g1ZElqYklKWVo4dGpHVW45NkNOZWcK31m5VOH30V2OUnJsZiRAEIFi10gljsP9
            zfzZQ3LjckWeiP3FacdXc+Ef+J4dhRd4+PMSO9C7UZovwxY3xzgZ1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-23T03:00:02Z"
    mac: ENC[AES256_GCM,data:O0fd/Pm8sLYmA5gsW3723HtrNUeyfTi1zNvkuo7P6abZF3QMTfg19XRXPusBYHEt+QI6CH7IWnyDQkNPcGU7eSyoxU1mgaMsnPzIv3khib/blZXYiKZyLZ7lRRXuHjL9yjzNQDcVXHkR36Y2Mmmxscud6uUe59wBezdtbNUssxE=,iv:1C7CBNKmmjilEm+J9Zi4f9XrLHDZJcbvur5qTbpiOw4=,tag:oZEv6wmnhV2Xu2u4QqlYIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
