apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: trakt-client-secret
stringData:
    id: ENC[AES256_GCM,data:iBMpw5fDiqQ50td8a0XtDZOD09H+aMCrf3ss2S/6tNYCSoXgVxkQagNkjiuZ/iVrzG6ezj3qoI9j1pFqbUpLNA==,iv:j/YdoyLMAVkq4RP0ChiUpzQz4Sm7cmIebz0PRrLa9iA=,tag:5XP1Xb2Z4K0/R8dcUJzX4A==,type:str]
    secret: ENC[AES256_GCM,data:m0tmC6GLpg5IU8jcmJEme4LUNm2SRq1yXUpjxrLCICL9IZi5OEOdkm2gMVSzs4XY/Ipga4IN5nFP2m/fzj+n3Q==,iv:yp6LUBJBg2Z1COaADbHQuVx8iI6h8O5EzdBdwsO6Cos=,tag:iEznSZXvS6iR9BbGg5wshg==,type:str]
    pin: ENC[AES256_GCM,data:9Fefn5I+Gzg=,iv:ezaq/ZJVqIWm6P6+0BuK/kSfrL+199KYXY4weGffUVI=,tag:7W5OVcbIOSuKRMYKZRBp1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSDVmWHZmcno3Z3h2RTIw
            eE9kZC9lc2Q5WHdqcVFLR1RZSG05M1VhYzJvCmc0VFNpM3BMTjNwMDdIc3RqN3Ra
            aTh0Q20yZktzRUg5VmdrVmVXc3YyancKLS0tIFV6V1huTldqYU16RGZnMkd1QmVQ
            WDJxTUdvWDVOZWdoN2ZtazYxR0tqS1kKKwsYiUGQEhS2XYe1IDnFNf5ALh5IWSD/
            l+a/yqF/luBb442M7S6OvFWnSyc03cNTyKwpGt3Jrz5coC/KZrh+gg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pc3uygu2npxjhz43rufgsad3wt7skff4792zlg7mk69uwm4stqpqjz9mll
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-27T14:57:45Z"
    mac: ENC[AES256_GCM,data:+qEVkry7V2+/2H4wXmePSxy/qKoCu8vRLu79O+VjrXUqKcIJzH6FCbmlGR+68NNXLLzJZ38rOSUa9JsRuTydSGrt56Labxzclo//vwqv1XEY7Oc54KTbioEbbKSyEKN03nvnsAw0lPZsKJ6OI2ySADHDSJhXcv7qJZiMFG7Zp5U=,iv:c3nMyP9SfpkLgaQqHK+PkeRZ5vPjHNjmcdu2hWQ46t8=,tag:bR8klM+70Ppyj80dvGdksA==,type:str]
    version: 3.13.1
