apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transmission-openvpn.fullname" . }}
  labels:
  {{- include "transmission-openvpn.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.secretEnv | nindent 2 }}
