#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  repository: linuxserver/ddclient
  pullPolicy: IfNotPresent
  tag: version-v3.9.1

strategy:
  type: Recreate

env: 
#  DOMAIN: sbarre
#  TLD: ca
#  CF_EMAIL: fishfu@gmail.com
#  CF_GLOBAL_APIKEY: 18jqSND8wGcwhr7Tz5CMeK3jcx0LjrRe0-5Gfjwb
  # TZ:
  # PUID:
  # PGID:

service:
  enabled: false

ingress:
  enabled: false

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

config: |
  # This is the configuration for ddclient
  # Inorder for it to function you need to set it up
  # e.g. this is the config for Cloudflare
  daemon=600
  use=web
  web=dynamicdns.park-your-domain.com/getip
  protocol=cloudflare
  ssl=yes
  ttl=1
  login=token
  password=18jqSND8wGcwhr7Tz5CMeK3jcx0LjrRe0-5Gfjwb
  zone=stephenbarre.ca
  *.stephenbarre.ca
  plex.stephenbarre.ca
  ombi.stephenbarre.ca
