apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: tautulli-config
provisioner: kubekrnetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tautulli-config-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: "tautulli-config"
  nfs:
    server: "192.168.1.4"
    path: "/export/tautulli/config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "tautulli-config"
  resources:
    requests:
      storage: 1Gi
