apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: tautulli-config
provisioner: kubekrnetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tautulli-config-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: "tautulli-config"
  local:
    path: /home/stephen/data/tautulli/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-main
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "tautulli-config"
  resources:
    requests:
      storage: 1Gi
