# Default values for tautulli.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: linuxserver/tautulli
  tag: v2.1.44-ls34
  pullPolicy: IfNotPresent

# upgrade strategy type (e.g. Recreate or RollingUpdate)
strategyType: Recreate

# Probes configuration
probes:
  liveness:
    initialDelaySeconds: 60
    failureThreshold: 5
    timeoutSeconds: 10
  readiness:
    initialDelaySeconds: 60
    failureThreshold: 5
    timeoutSeconds: 10

nameOverride: ""
fullnameOverride: ""

timezone: "America/New York"
puid: 1000
pgid: 1000

service:
  type: LoadBalancer
  port: 80
  annotations: {}
  labels: {}
  loadBalancerIP: 192.168.1.243

persistence:
  config:
    enabled: true
    existingClaim: tautulli-config
    accessMode: ReadWriteMany
    size: 1Gi
    subPath: ""
    skipuninstall: false

resources: 
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

deploymentAnnotations: {}

