# Default values for tautulli.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: linuxserver/tautulli
  tag: latest
  pullPolicy: Always

# upgrade strategy type (e.g. Recreate or RollingUpdate)
strategyType: Recreate

# Probes configuration
probes:
  liveness:
    initialDelaySeconds: 60
    failureThreshold: 5
    timeoutSeconds: 10
  readiness:
    initialDelaySeconds: 60
    failureThreshold: 5
    timeoutSeconds: 10

nameOverride: ""
fullnameOverride: ""

timezone: "America/New York"
puid: 1000
pgid: 1000

#service:
#  type: LoadBalancer
#  port: 80
#  annotations: {}
#  labels: {}
#  loadBalancerIP: 192.168.1.243

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    #traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    #traefik.ingress.kubernetes.io/router.tls: "true"
    #traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    #traefik.ingress.kubernetes.io/router.tls.domains.0.main: tautulli.stephenbarre.ca
  path: /
  hosts:
    - tautulli.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

persistence:
  config:
    enabled: true
    existingClaim: tautulli-config
    accessMode: ReadWriteMany
    size: 1Gi
    subPath: ""
    skipuninstall: false

resources: 
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

deploymentAnnotations:
  co.elastic.monitor/type: http
  co.elastic.monitor/urls: "http://${data.host}:{$data.port}/"
  co.elastic.monitor/schedule: "@every 10s"
  co.elastic.monitor/name: "Tautulli"



