kind: Service 
apiVersion: v1
metadata:
  name: transmission-transmission-openvpn-lb
  namespace: plex
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9091
  selector:
    app: transmission-openvpn
    release: transmission
  type: LoadBalancer
  loadBalancerIP: 192.168.1.200
