# Optimized for airvpn.

replicaCount: 1

image:
  repository: haugene/transmission-openvpn
  tag: latest
  pullPolicy: IfNotPresent

dnsPolicy: "None"

dnsConfig:
  nameservers:
    - 8.8.8.8
    - 8.8.4.4

env:
  - name: OPENVPN_PROVIDER
    value: "NORDVPN" # VPN provider. List of supported providers: https://haugene.github.io/docker-transmission-openvpn/supported-providers/
  - name: OPENVPN_USERNAME
    valueFrom: # Reference to the secret | openvpn.username
      secretKeyRef:
        name: "openvpn"
        key: "username"
  - name: OPENVPN_PASSWORD
    valueFrom: # Reference to the secret | openvpn.password
      secretKeyRef:
        name: "openvpn"
        key: "password"
  - name: NORDVPN_PROTOCOL
    value: "TCP"
  - name: NORDVPN_COUNTRY
    value: "US" # Country where we want to download over VPN
  - name: NORDVPN_CATEGORY
    value: "P2P" # VPN Type
  - name: LOCAL_NETWORK
    value: "192.168.1.0/24"
  - name: TRANSMISSION_PEER_PORT
    value: "47444"
  - name: TRANSMISSION_DOWNLOAD_DIR
    value: "/downloads/transmission"
  - name: TRANSMISSION_DOWNLOAD_QUEUE_SIZE
    value: "200"
  - name: TRANSMISSION_RATIO_LIMIT
    value: "1"
  - name: TRANSMISSION_RATIO_LIMIT_ENABLED
    value: "true"
  - name: TRANSMISSION_PEER_LIMIT_PER_TORRENT
    value: "200"
  - name: TRANSMISSION_PEER_LIMIT_GLOBAL
    value: "2000"
  - name: TRANSMISSION_CACHE_SIZE_MB
    value: "16"
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

service:
  type: ClusterIP
  port: 80

# You have 2 options to deploy your custom openvpn config:
#
# 1. Create a kubernetes secret manually from an openvpn config file like this:
#
#    kubectl create configmap openvpn-common-config --from-file openvpn.conf --namespace usr-jean-saisrien
#
# 2. Use the `customOpenvpnConfig` config option, which will be used
# to store a kubernetes secret on your cluster automatically:
#
#customOpenvpnConfig:
#  secretName: privatevpn-amsterdam1-udp-1194
#  fileName: privatevpn-amsterdam1-udp-1194.ovpn
#  config: |
#    remote nl-ams.pvdata.host 1194 udp
#    nobind
#    dev tun
#   …

volumes:
  - name: "config"
    persistentVolumeClaim:
      claimName: "transmission-config" # PersistentVolumeClaim created earlier
  - name: "downloads"
    persistentVolumeClaim:
      claimName: "transmission-downloads" # PersistentVolumeClaim created earlier
  - name: "dev-tun" # Needed for VPN
    hostPath:
      path: "/dev/net/tun"

volumeMounts:
  - name: "config"
    mountPath: "/data"
    subPath: "" # Path /mnt/ssd/media/configs/transmission-data where transmission writes the configuration
  - name: "downloads"
    mountPath: "/downloads/transmission"
    subPath: "" # Path /mnt/ssd/media/downloads/transmission where transmission downloads Torrents
  - name: "dev-tun"
    mountPath: "/dev/net/tun" # Needed for VPN
# Security context for container
securityContext:
  capabilities:
    add:
      - NET_ADMIN

podSecurityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

