apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stephenbarre.ca
  namespace: plex
spec:
  commonName: "stephenbarre.ca"
  dnsNames:
    - "stephenbarre.ca"
    - "*.stephenbarre.ca"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  secretName: tls
