image:
  tag: latest
  pullPolicy: Always

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: local
    hosts:
      - host: "nzbget.local"
        paths:
          - path: "/"

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /mnt/extra/qbittorrent-config
    mountPath: /config
  video:
    enabled: true
    type: hostPath
    hostPath: /mnt/plex
    mountPath: /data
  books:
    enabled: true
    type: hostPath
    hostPath: /mnt/extra/calibre/config/downloads
    mountPath: /books

resources: {}
