repositories:
  - name: ks8-at-home
    url: https://k8s-at-home.com/charts/
  - name: ks8-at-home-common
    url: https://library-charts.k8s-at-home.com
helmDefaults:
  skipDeps: true

templates:
  kahData: &kahData
    chart: k8s-at-home/{{`{{ .Release.Name }}`}}
    namespace: plex
    values:
      - ./k8s_at_home/{{`{{ .Release.Name }}`}}.values.yaml
    valuesTemplate:
      - persistence:
          data:
            enabled: true
            type: hostPath
            hostPath: /mnt/plex
            accessMode: "ReadWriteMany"
            mountPath: /data
  kahNoData: &kahNoData
    chart: k8s-at-home/{{`{{ .Release.Name }}`}}
    namespace: plex
    values:
      - ./k8s_at_home/{{`{{ .Release.Name }}`}}.values.yaml
  basic: &basic
    chart: ./{{`{{ .Release.Name }}`}}/{{`{{ .Release.Name }}`}}
    values:
      - ./{{`{{ .Release.Name }}`}}/values.yaml
    namespace: plex

releases:
  - name: jackett
    <<: *kahNoData
  - name: ombi
    <<: *kahNoData
  - name: plex
    <<: *kahData
  - name: radarr
    <<: *kahData
  - name: sonarr
    <<: *kahData
  - name: nzbget
    <<: *kahData
  - name: tautulli
    <<: *kahNoData
  - name: transmission-openvpn
    recreatePods: true
    installed: false
    <<: *basic
  - name: qbittorrent-pia
    recreatePods: true
    installed: true
    <<: *basic
  - name: plex-meta-manager
    recreatePods: true
    installed: true
    <<: *basic
  - name: prowlarr
    <<: *kahNoData